// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : dansand
Date           : Thu Oct  6 19:25:31 2016
Host           : Linux cmsbuild17.cern.ch 2.6.32-431.29.2.el6.x86_64 #1 SMP Wed Sep 10 11:13:12 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/dansand/CMSDAS15/CMSSW_7_3_0/src/Analysis/B2GDAS/test/DESYBDT/80X/lept
Training events: 1759702
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "150" [Max depth of the decision tree allowed]
MinNodeSize: "5" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "25" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
DRpt                          DRpt                          DRpt                          DRpt                                                            'F'    [0.00168255029712,9.17481613159]
ht_met_lep_norm               ht_met_lep_norm               ht_met_lep_norm               ht_met_lep_norm                                                 'F'    [0.181815564632,16.2598876953]
lep1__minDR_jet               lep1__minDR_jet               lep1__minDR_jet               lep1__minDR_jet                                                 'F'    [0.0128279421479,4.78038072586]
lep1__pTrel_jet_norm          lep1__pTrel_jet_norm          lep1__pTrel_jet_norm          lep1__pTrel_jet_norm                                            'F'    [0.0010531732114,2.29247522354]
jet1_csv                      jet1_csv                      jet1_csv                      jet1_csv                                                        'F'    [0.0209744982421,0.999228954315]
jet1_pt                       jet1_pt                       jet1_pt                       jet1_pt                                                         'F'    [0.0443222820759,7.86185455322]
jet1_m                        jet1_m                        jet1_m                        jet1_m                                                          'F'    [-0.0110585857183,1.23307979107]
jet2_csv                      jet2_csv                      jet2_csv                      jet2_csv                                                        'F'    [0.0138477738947,0.999490857124]
jet2_pt                       jet2_pt                       jet2_pt                       jet2_pt                                                         'F'    [0.00636615557596,6.34561729431]
jet2_m                        jet2_m                        jet2_m                        jet2_m                                                          'F'    [-0.0285268686712,1.2399750948]
njets                         njets                         njets                         njets                                                           'I'    [2,15]
s33                           s33                           s33                           s33                                                             'F'    [3.40490714734e-06,0.967006444931]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "DRpt", "ht_met_lep_norm", "lep1__minDR_jet", "lep1__pTrel_jet_norm", "jet1_csv", "jet1_pt", "jet1_m", "jet2_csv", "jet2_pt", "jet2_m", "njets", "s33" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'I';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.744109706598083);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.926027,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.830597,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241555,-99) , 
10, -0.786982, 0, 0, 0.385663,-99) , 
4, 0.0769231, 0, 0, 0.567054,-99) , 
7, 0.0838464, 0, 0, 0.736731,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550537,-99) , 
NN(
0, 
0, 
-1, 0.307447, 0, -1, 0.128618,-99) , 
7, 0.384615, 0, 0, 0.188647,-99) , 
0, -0.923077, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.587606);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.934548, 1, 1, 0.810304,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.737495,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382598,-99) , 
7, -0.43094, 0, 0, 0.503592,-99) , 
NN(
0, 
0, 
-1, -0.9153, 1, -1, 0.202878,-99) , 
2, -0.772244, 1, 0, 0.282819,-99) , 
7, 0.615385, 0, 0, 0.361893,-99) , 
4, 0.384615, 0, 0, 0.476637,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.452811);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.859968,-99) , 
NN(
NN(
0, 
0, 
-1, 0.230243, 1, 1, 0.641919,-99) , 
NN(
0, 
0, 
-1, -0.935186, 1, -1, 0.405529,-99) , 
4, -0.307692, 0, 0, 0.527018,-99) , 
7, 0.389194, 0, 0, 0.628677,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583469,-99) , 
NN(
0, 
0, 
-1, -0.692308, 0, -1, 0.312094,-99) , 
4, 0.0767597, 0, 0, 0.389727,-99) , 
NN(
0, 
0, 
-1, -0.549851, 1, -1, 0.143264,-99) , 
0, -0.849112, 1, 0, 0.290149,-99) , 
0, -0.923077, 1, 0, 0.483711,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.355741);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0076085, 0, 1, 0.697107,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566804,-99) , 
NN(
0, 
0, 
-1, -0.692308, 0, -1, 0.389268,-99) , 
7, -0.0690985, 0, 0, 0.460298,-99) , 
8, -0.922649, 1, 0, 0.59547,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528232,-99) , 
NN(
0, 
0, 
-1, -0.880627, 1, -1, 0.326587,-99) , 
2, -0.428994, 1, 0, 0.424067,-99) , 
NN(
0, 
0, 
-1, -0.846154, 0, -1, 0.144501,-99) , 
8, -0.923077, 1, 0, 0.313351,-99) , 
2, -0.615385, 1, 0, 0.493881,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.299931);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.730487,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626569,-99) , 
NN(
NN(
0, 
0, 
-1, -0.538464, 0, 1, 0.569497,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424849,-99) , 
11, 0.230522, 1, 0, 0.462413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30577,-99) , 
8, -0.924416, 1, 0, 0.400415,-99) , 
10, -0.692308, 0, 0, 0.464252,-99) , 
2, -0.852071, 1, 0, 0.506297,-99) , 
7, 0.541868, 0, 0, 0.555776,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376573,-99) , 
8, -0.949497, 1, 0, 0.471099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.284569,-99) , 
10, -0.923077, 0, 0, 0.424231,-99) , 
NN(
0, 
0, 
-1, -0.463014, 1, -1, 0.194246,-99) , 
8, -0.923077, 1, 0, 0.338412,-99) , 
2, -0.615385, 1, 0, 0.478455,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.287237);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.700774,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.374068, 0, 1, 0.565718,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557823,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385372,-99) , 
7, -0.461564, 0, 0, 0.444763,-99) , 
NN(
0, 
0, 
-1, -0.650888, 0, -1, 0.330277,-99) , 
8, -0.929667, 1, 0, 0.397273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.203233,-99) , 
10, -0.923077, 0, 0, 0.360524,-99) , 
6, -0.882088, 0, 0, 0.410085,-99) , 
0, -0.95858, 1, 0, 0.459665,-99) , 
NN(
0, 
0, 
-1, -0.775148, 1, -1, 0.239203,-99) , 
0, -0.846154, 1, 0, 0.42592,-99) , 
4, 0.692308, 0, 0, 0.464152,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.262185);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658672,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585084,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477492,-99) , 
7, -0.591717, 1, 0, 0.513757,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582551,-99) , 
NN(
0, 
0, 
-1, -0.696365, 1, -1, 0.428341,-99) , 
8, -0.952093, 1, 0, 0.474986,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329068,-99) , 
1, -0.927951, 0, 0, 0.426859,-99) , 
NN(
0, 
0, 
-1, -0.840237, 0, -1, 0.241088,-99) , 
5, -0.926976, 1, 0, 0.344767,-99) , 
6, -0.913813, 0, 0, 0.396944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.224801,-99) , 
8, -0.846154, 1, 0, 0.377719,-99) , 
10, -0.461538, 0, 0, 0.400503,-99) , 
4, 0.692308, 0, 0, 0.424294,-99) , 
7, 0.769231, 0, 0, 0.451673,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.205163);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612775,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.614728, 0, 1, 0.581981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402717,-99) , 
8, -0.845164, 1, 0, 0.527241,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500509,-99) , 
NN(
0, 
0, 
-1, -0.853829, 0, -1, 0.398701,-99) , 
5, -0.932322, 1, 0, 0.441258,-99) , 
6, -0.901303, 0, 0, 0.480229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334498,-99) , 
10, -0.923077, 0, 0, 0.464225,-99) , 
7, 0.618294, 0, 0, 0.490107,-99) , 
NN(
0, 
0, 
-1, -0.931839, 1, -1, 0.358681,-99) , 
2, -0.538462, 1, 0, 0.456385,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.196431);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578581,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469818,-99) , 
7, -0.676627, 0, 0, 0.554118,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33924,-99) , 
6, -0.843803, 0, 0, 0.425097,-99) , 
8, -0.892076, 1, 0, 0.506146,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445292,-99) , 
5, -0.941631, 1, 0, 0.48856,-99) , 
NN(
0, 
0, 
-1, -0.871036, 0, -1, 0.373632,-99) , 
8, -0.956319, 1, 0, 0.414743,-99) , 
6, -0.910218, 0, 0, 0.454675,-99) , 
4, 0.615385, 0, 0, 0.474646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.247511,-99) , 
0, -0.769231, 1, 0, 0.463139,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.182853);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597568,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.00102368, 1, 1, 0.543303,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45698,-99) , 
8, -0.939681, 1, 0, 0.535254,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509004,-99) , 
NN(
0, 
0, 
-1, -0.921515, 0, -1, 0.340419,-99) , 
6, -0.8939, 0, 0, 0.413399,-99) , 
5, -0.913285, 1, 0, 0.462088,-99) , 
10, -0.692308, 0, 0, 0.491995,-99) , 
NN(
0, 
0, 
-1, -0.967217, 1, -1, 0.384719,-99) , 
1, -0.9216, 0, 0, 0.466655,-99) , 
7, 0.692308, 0, 0, 0.484433,-99) , 
NN(
0, 
0, 
-1, -0.819222, 0, -1, 0.358494,-99) , 
8, -0.846154, 1, 0, 0.468065,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.168682);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542352,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606966,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514407,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335249,-99) , 
8, -0.962333, 1, 0, 0.423323,-99) , 
1, -0.918088, 0, 0, 0.460972,-99) , 
11, -0.153829, 1, 0, 0.490629,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555212,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415907,-99) , 
0, -0.923501, 0, 0, 0.481835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340208,-99) , 
0, -0.867515, 1, 0, 0.443017,-99) , 
6, -0.826039, 0, 0, 0.46644,-99) , 
NN(
0, 
0, 
-1, -0.921477, 1, -1, 0.345648,-99) , 
10, -0.846154, 0, 0, 0.423378,-99) , 
5, -0.922766, 1, 0, 0.450448,-99) , 
2, -0.846154, 1, 0, 0.466742,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.154612);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591402,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533609,-99) , 
NN(
0, 
0, 
-1, -0.914068, 0, -1, 0.415297,-99) , 
8, -0.970374, 1, 0, 0.451821,-99) , 
7, -4.78625e-05, 0, 0, 0.496127,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52075,-99) , 
NN(
0, 
0, 
-1, -0.526671, 0, -1, 0.448493,-99) , 
11, -0.154729, 1, 0, 0.475679,-99) , 
NN(
0, 
0, 
-1, -0.692308, 0, -1, 0.404706,-99) , 
4, -0.461541, 0, 0, 0.444498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314742,-99) , 
2, -0.376665, 1, 0, 0.430644,-99) , 
9, -0.923077, 1, 0, 0.458867,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.146356);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46273,-99) , 
8, -0.910875, 1, 0, 0.543472,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527664,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581404,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438384,-99) , 
4, -0.00511334, 1, 0, 0.470889,-99) , 
7, -0.221372, 0, 0, 0.515428,-99) , 
NN(
0, 
0, 
-1, -0.911369, 0, -1, 0.446237,-99) , 
4, -0.53724, 0, 0, 0.487775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389012,-99) , 
1, -0.937045, 0, 0, 0.468522,-99) , 
NN(
0, 
0, 
-1, -0.837172, 0, -1, 0.390382,-99) , 
8, -0.902367, 1, 0, 0.453405,-99) , 
10, -0.461538, 0, 0, 0.466005,-99) , 
11, -0.538462, 1, 0, 0.479033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343739,-99) , 
8, -0.769231, 1, 0, 0.47127,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.125061);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594894,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474451,-99) , 
4, -0.304733, 1, 0, 0.49311,-99) , 
7, 0.160255, 0, 0, 0.524905,-99) , 
NN(
0, 
0, 
-1, -0.774071, 0, -1, 0.445222,-99) , 
4, -0.615385, 0, 0, 0.502005,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494264,-99) , 
1, -0.839475, 0, 0, 0.530049,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43341,-99) , 
1, -0.913877, 0, 0, 0.477495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351012,-99) , 
8, -0.925479, 1, 0, 0.442988,-99) , 
10, -0.692308, 0, 0, 0.470287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376146,-99) , 
7, 0.384615, 1, 0, 0.452077,-99) , 
2, -0.692308, 1, 0, 0.478152,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.140469);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585949,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.931072, 1, 1, 0.554418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449541,-99) , 
1, -0.941065, 0, 0, 0.52927,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583508,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407554,-99) , 
7, -0.538593, 0, 0, 0.47157,-99) , 
1, -0.880146, 0, 0, 0.515761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453712,-99) , 
5, -0.891632, 1, 0, 0.494149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372733,-99) , 
1, -0.918006, 0, 0, 0.479281,-99) , 
8, -0.946333, 1, 0, 0.501433,-99) , 
NN(
0, 
0, 
-1, -0.846154, 0, -1, 0.398822,-99) , 
0, -0.876658, 1, 0, 0.486152,-99) , 
6, -0.834652, 0, 0, 0.494407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382814,-99) , 
8, -0.769231, 1, 0, 0.488078,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.108603);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551295,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535016,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510986,-99) , 
NN(
0, 
0, 
-1, 0.212805, 1, -1, 0.434234,-99) , 
10, -0.846154, 1, 0, 0.458135,-99) , 
11, -0.461585, 1, 0, 0.476251,-99) , 
4, -0.0769231, 0, 0, 0.507793,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552498,-99) , 
NN(
0, 
0, 
-1, -0.932156, 0, -1, 0.473549,-99) , 
11, 1.44839e-05, 1, 0, 0.496353,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436534,-99) , 
5, -0.846327, 1, 0, 0.493382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330733,-99) , 
10, -0.846154, 0, 0, 0.435595,-99) , 
5, -0.92018, 1, 0, 0.465208,-99) , 
2, -0.692308, 1, 0, 0.487516,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.12061);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529367,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.453639, 1, 1, 0.57498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432846,-99) , 
10, -0.846154, 0, 0, 0.52619,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466704,-99) , 
4, -0.414012, 1, 0, 0.513037,-99) , 
NN(
0, 
0, 
-1, 0.0763003, 1, -1, 0.431611,-99) , 
10, -0.846154, 1, 0, 0.464118,-99) , 
0, -0.923077, 0, 0, 0.490559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436914,-99) , 
7, 0.384615, 1, 0, 0.47921,-99) , 
4, 0.692308, 0, 0, 0.485826,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.128667);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566428,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542154,-99) , 
NN(
0, 
0, 
-1, -0.932196, 0, -1, 0.446226,-99) , 
1, -0.90959, 0, 0, 0.491322,-99) , 
5, -0.949704, 1, 0, 0.518539,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546664,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556035,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455432,-99) , 
1, -0.843444, 0, 0, 0.49844,-99) , 
0, -0.946614, 1, 0, 0.523236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432949,-99) , 
6, -0.928821, 0, 0, 0.505799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400573,-99) , 
5, -0.82926, 1, 0, 0.487744,-99) , 
6, -0.823612, 0, 0, 0.498668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408385,-99) , 
10, -0.923077, 0, 0, 0.48908,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396063,-99) , 
2, -0.475336, 1, 0, 0.475887,-99) , 
5, -0.923077, 1, 0, 0.491742,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.118484);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561595,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546174,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.840138, 0, 1, 0.546347,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474098,-99) , 
4, -0.305763, 0, 0, 0.517149,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47921,-99) , 
5, -0.926676, 1, 0, 0.513442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438635,-99) , 
10, -0.804734, 1, 0, 0.476081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414875,-99) , 
4, 0.0773238, 1, 0, 0.45623,-99) , 
7, -0.153886, 0, 0, 0.480212,-99) , 
1, -0.865324, 0, 0, 0.493368,-99) , 
NN(
0, 
0, 
-1, -0.821709, 0, -1, 0.412516,-99) , 
8, -0.887005, 1, 0, 0.482288,-99) , 
1, -0.756183, 0, 0, 0.488042,-99) , 
8, -0.973373, 1, 0, 0.49619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404233,-99) , 
8, -0.769231, 1, 0, 0.491074,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.104726);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548036,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589342,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560994,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420502,-99) , 
0, -0.874832, 1, 0, 0.468357,-99) , 
10, -0.692308, 0, 0, 0.505868,-99) , 
4, -0.30759, 0, 0, 0.531795,-99) , 
NN(
NN(
0, 
0, 
-1, -0.921806, 0, 1, 0.538955,-99) , 
NN(
0, 
0, 
-1, 0.153093, 1, -1, 0.45983,-99) , 
10, -0.846154, 1, 0, 0.491032,-99) , 
0, -0.923077, 0, 0, 0.508507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415147,-99) , 
7, 0.360946, 1, 0, 0.496832,-99) , 
NN(
0, 
0, 
-1, 0.0766641, 1, -1, 0.451586,-99) , 
4, 0.384615, 1, 0, 0.486746,-99) , 
7, 0.769231, 0, 0, 0.493246,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0852833);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56686,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547687,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.930451, 0, 1, 0.535383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487904,-99) , 
8, -0.940635, 1, 0, 0.520059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4552,-99) , 
5, -0.906124, 1, 0, 0.507276,-99) , 
1, -0.86267, 0, 0, 0.514784,-99) , 
NN(
0, 
0, 
-1, -0.77795, 0, -1, 0.470326,-99) , 
5, -0.864545, 1, 0, 0.505786,-99) , 
11, -0.69229, 1, 0, 0.511722,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396733,-99) , 
6, -0.928333, 0, 0, 0.457845,-99) , 
10, -0.923077, 0, 0, 0.504589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431789,-99) , 
0, -0.804467, 1, 0, 0.50034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435454,-99) , 
3, -0.769231, 1, 0, 0.495666,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0708719);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.937904, 1, 1, 0.54106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472291,-99) , 
7, -0.755861, 0, 0, 0.528256,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441851,-99) , 
10, -0.846154, 0, 0, 0.476225,-99) , 
6, -0.923077, 0, 0, 0.510307,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.910076, 0, 1, 0.53061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504712,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456691,-99) , 
7, -0.599358, 0, 0, 0.482577,-99) , 
2, -0.431951, 0, 0, 0.501017,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449751,-99) , 
2, -0.617887, 0, 0, 0.477019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371487,-99) , 
2, -0.477313, 1, 0, 0.443261,-99) , 
8, -0.923077, 1, 0, 0.481427,-99) , 
2, -0.692308, 1, 0, 0.496607,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0954146);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588493,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490654,-99) , 
7, -0.603424, 0, 0, 0.514724,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467375,-99) , 
11, 0.153327, 1, 0, 0.495405,-99) , 
3, -0.970894, 1, 0, 0.521295,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488816,-99) , 
4, -0.538589, 1, 0, 0.497417,-99) , 
NN(
0, 
0, 
-1, -0.902432, 1, -1, 0.45715,-99) , 
10, -0.692308, 0, 0, 0.475823,-99) , 
3, -0.920662, 1, 0, 0.501218,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557579,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402694,-99) , 
5, -0.944405, 1, 0, 0.466166,-99) , 
1, -0.904768, 0, 0, 0.494606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367047,-99) , 
5, -0.903636, 1, 0, 0.475189,-99) , 
6, -0.923077, 0, 0, 0.490719,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.113676);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485374,-99) , 
3, -0.92804, 1, 0, 0.535112,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588651,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477464,-99) , 
8, -0.902723, 1, 0, 0.5107,-99) , 
2, -0.716764, 1, 0, 0.533722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469917,-99) , 
0, -0.921494, 0, 0, 0.507399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442104,-99) , 
7, 0.312829, 1, 0, 0.492253,-99) , 
9, -0.923077, 1, 0, 0.506244,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555827,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411327,-99) , 
1, -0.911047, 0, 0, 0.481952,-99) , 
5, -0.946359, 1, 0, 0.505188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396911,-99) , 
1, -0.945582, 0, 0, 0.484645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389481,-99) , 
5, -0.903636, 1, 0, 0.470255,-99) , 
6, -0.923077, 0, 0, 0.491751,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0805772);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56123,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540434,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.904931, 1, 1, 0.53456,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472228,-99) , 
7, -0.595658, 0, 0, 0.498283,-99) , 
8, -0.922399, 0, 0, 0.512823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461185,-99) , 
8, -0.88111, 1, 0, 0.504358,-99) , 
1, -0.781834, 0, 0, 0.512195,-99) , 
8, -0.963689, 1, 0, 0.519672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451093,-99) , 
8, -0.768503, 1, 0, 0.513462,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498527,-99) , 
2, -0.597791, 1, 0, 0.52039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441297,-99) , 
0, -0.90327, 1, 0, 0.497058,-99) , 
NN(
0, 
0, 
-1, -0.970085, 0, -1, 0.441184,-99) , 
3, -0.94017, 0, 0, 0.47036,-99) , 
6, -0.923077, 0, 0, 0.496133,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0658337);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.0779843, 1, 1, 0.538413,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.91471, 0, 1, 0.564833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497704,-99) , 
10, -0.846154, 1, 0, 0.526219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466146,-99) , 
1, -0.93689, 0, 0, 0.512594,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463187,-99) , 
1, -0.891053, 0, 0, 0.492144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438515,-99) , 
0, -0.899522, 1, 0, 0.474784,-99) , 
5, -0.909506, 1, 0, 0.496494,-99) , 
6, -0.846154, 0, 0, 0.502831,-99) , 
NN(
0, 
0, 
-1, -0.700858, 0, -1, 0.46838,-99) , 
4, -0.769231, 0, 0, 0.496496,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0633888);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536752,-99) , 
NN(
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.30759, 0, 1, 0.544348,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493762,-99) , 
10, -0.781065, 1, 0, 0.510544,-99) , 
0, -0.929954, 0, 0, 0.527419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467763,-99) , 
4, 0.384615, 1, 0, 0.514646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485677,-99) , 
7, 0.384615, 1, 0, 0.508629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48218,-99) , 
2, -0.855308, 0, 0, 0.50414,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408991,-99) , 
8, -0.948945, 1, 0, 0.476329,-99) , 
10, -0.923077, 0, 0, 0.500782,-99) , 
11, -0.769231, 1, 0, 0.503495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465294,-99) , 
3, -0.769231, 1, 0, 0.500746,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0761491);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574681,-99) , 
NN(
NN(
0, 
0, 
-1, 0.378475, 1, 1, 0.537349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472559,-99) , 
0, -0.925163, 0, 0, 0.498808,-99) , 
7, 0.236599, 0, 0, 0.51794,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579293,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486092,-99) , 
1, -0.908739, 0, 0, 0.516054,-99) , 
NN(
0, 
0, 
-1, -0.926783, 1, -1, 0.480412,-99) , 
0, -0.9153, 1, 0, 0.497417,-99) , 
7, -0.254474, 0, 0, 0.517093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483166,-99) , 
2, -0.76917, 0, 0, 0.506669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451119,-99) , 
7, 0.384551, 1, 0, 0.495016,-99) , 
4, -0.153846, 0, 0, 0.504525,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0975785);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566965,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549034,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48334,-99) , 
8, -0.946104, 1, 0, 0.50348,-99) , 
6, -0.920361, 0, 0, 0.521921,-99) , 
4, 0.231874, 0, 0, 0.535218,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483536,-99) , 
6, -0.900598, 1, 0, 0.536693,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483255,-99) , 
1, -0.91646, 0, 0, 0.523107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438301,-99) , 
5, -0.908738, 1, 0, 0.50242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394895,-99) , 
8, -0.93181, 1, 0, 0.476502,-99) , 
1, -0.867962, 0, 0, 0.494586,-99) , 
0, -0.943978, 1, 0, 0.515051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536738,-99) , 
NN(
0, 
0, 
-1, -0.802204, 1, -1, 0.445304,-99) , 
6, -0.819222, 0, 0, 0.485833,-99) , 
5, -0.846154, 1, 0, 0.509629,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0861812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553761,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575355,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484164,-99) , 
1, -0.906969, 0, 0, 0.521988,-99) , 
5, -0.936501, 1, 0, 0.542338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495482,-99) , 
10, -0.692308, 1, 0, 0.527149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455368,-99) , 
1, -0.933606, 0, 0, 0.512808,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.902121, 1, 1, 0.526336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467063,-99) , 
8, -0.869914, 1, 0, 0.508581,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402182,-99) , 
6, -0.89838, 0, 0, 0.456826,-99) , 
1, -0.87279, 0, 0, 0.487699,-99) , 
5, -0.912878, 1, 0, 0.500397,-99) , 
9, -0.939299, 1, 0, 0.506381,-99) , 
9, -0.856525, 0, 0, 0.509145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457737,-99) , 
8, -0.769231, 1, 0, 0.506329,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0724736);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536038,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.284027, 0, 1, 0.54539,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469907,-99) , 
8, -0.944617, 1, 0, 0.507301,-99) , 
10, -0.846154, 0, 0, 0.530452,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434085,-99) , 
7, -0.468817, 1, 0, 0.485172,-99) , 
2, -0.772244, 0, 0, 0.513022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482185,-99) , 
4, 0.384615, 1, 0, 0.506013,-99) , 
7, 0.692308, 0, 0, 0.509948,-99) , 
NN(
0, 
0, 
-1, -0.449328, 1, -1, 0.479762,-99) , 
3, -0.846154, 1, 0, 0.504879,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0600197);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53032,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.831985, 1, 1, 0.545879,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535066,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479644,-99) , 
11, -0.000111282, 0, 0, 0.496613,-99) , 
4, -0.289828, 0, 0, 0.509491,-99) , 
10, -0.692308, 0, 0, 0.524404,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519162,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464719,-99) , 
2, -0.726105, 0, 0, 0.48225,-99) , 
11, 0.153335, 1, 0, 0.499981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453659,-99) , 
0, -0.934911, 1, 0, 0.49321,-99) , 
0, -0.923077, 0, 0, 0.506328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460546,-99) , 
7, 0.615385, 1, 0, 0.49958,-99) , 
4, 0.538462, 0, 0, 0.505027,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.07187);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531864,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538939,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54708,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537164,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517615,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432719,-99) , 
3, -0.950766, 1, 0, 0.469075,-99) , 
8, -0.957877, 1, 0, 0.487389,-99) , 
5, -0.940546, 1, 0, 0.503193,-99) , 
1, -0.876512, 0, 0, 0.51054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451801,-99) , 
1, -0.945582, 0, 0, 0.503412,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486793,-99) , 
4, -0.46233, 0, 0, 0.507982,-99) , 
NN(
0, 
0, 
-1, -0.908696, 0, -1, 0.452206,-99) , 
9, -0.899409, 0, 0, 0.475115,-99) , 
5, -0.899731, 1, 0, 0.493191,-99) , 
9, -0.846154, 0, 0, 0.496708,-99) , 
7, 0.769231, 0, 0, 0.500355,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0658551);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534941,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494112,-99) , 
7, -0.524229, 0, 0, 0.522448,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557892,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493886,-99) , 
10, -0.64497, 1, 0, 0.512678,-99) , 
9, -0.889933, 0, 0, 0.525882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480835,-99) , 
7, 0.160093, 1, 0, 0.513311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47239,-99) , 
4, 0.38431, 1, 0, 0.504131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459259,-99) , 
8, -0.951277, 0, 0, 0.498359,-99) , 
9, -0.929091, 1, 0, 0.504996,-99) , 
NN(
0, 
0, 
-1, -0.934116, 1, -1, 0.450788,-99) , 
6, -0.937745, 0, 0, 0.494692,-99) , 
5, -0.955621, 1, 0, 0.498936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464787,-99) , 
5, -0.769231, 1, 0, 0.495833,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0470134);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519231,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.881537, 1, 1, 0.53775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496288,-99) , 
10, -0.846154, 0, 0, 0.527162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486142,-99) , 
2, -0.300578, 1, 0, 0.517979,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497671,-99) , 
10, -0.804734, 1, 0, 0.51022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470107,-99) , 
4, -0.808834, 0, 0, 0.499595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470888,-99) , 
4, -0.289944, 1, 0, 0.488792,-99) , 
0, -0.923077, 0, 0, 0.501064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470174,-99) , 
7, 0.615385, 1, 0, 0.496516,-99) , 
4, 0.538462, 0, 0, 0.500537,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0506021);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529413,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.692308, 1, 1, 0.535499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486619,-99) , 
2, -0.60296, 1, 0, 0.522597,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541532,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482809,-99) , 
2, -0.643091, 1, 0, 0.496723,-99) , 
2, -0.436448, 0, 0, 0.510781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461035,-99) , 
2, -0.772244, 0, 0, 0.49726,-99) , 
8, -0.923166, 0, 0, 0.507433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477742,-99) , 
7, 0.360946, 1, 0, 0.503771,-99) , 
NN(
0, 
0, 
-1, 0.0766641, 1, -1, 0.483634,-99) , 
4, 0.384615, 1, 0, 0.499301,-99) , 
7, 0.769231, 0, 0, 0.502417,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0717957);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555147,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548002,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473798,-99) , 
3, -0.877939, 1, 0, 0.505472,-99) , 
5, -0.923726, 0, 0, 0.514895,-99) , 
9, -0.931486, 1, 0, 0.527361,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545977,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462648,-99) , 
3, -0.950397, 1, 0, 0.507368,-99) , 
1, -0.851538, 0, 0, 0.518078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485116,-99) , 
11, 0.3071, 1, 0, 0.507837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42326,-99) , 
6, -0.93234, 0, 0, 0.495548,-99) , 
5, -0.915407, 1, 0, 0.511736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468012,-99) , 
1, -0.945274, 0, 0, 0.507855,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417272,-99) , 
5, -0.802204, 1, 0, 0.462314,-99) , 
6, -0.819222, 0, 0, 0.483734,-99) , 
5, -0.846154, 1, 0, 0.50337,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.058556);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527212,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48291,-99) , 
6, -0.901249, 1, 0, 0.528233,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4887,-99) , 
0, -0.923931, 0, 0, 0.510514,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499909,-99) , 
7, -0.686443, 1, 0, 0.505598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46716,-99) , 
5, -0.906837, 1, 0, 0.491248,-99) , 
NN(
0, 
0, 
-1, -0.547353, 0, -1, 0.45131,-99) , 
1, -0.911093, 0, 0, 0.476269,-99) , 
8, -0.961188, 1, 0, 0.488991,-99) , 
1, -0.872307, 0, 0, 0.498821,-99) , 
7, 0.307692, 0, 0, 0.505307,-99) , 
NN(
0, 
0, 
-1, -0.308624, 0, -1, 0.475808,-99) , 
5, -0.846154, 1, 0, 0.499821,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0562324);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530544,-99) , 
NN(
NN(
0, 
0, 
-1, -0.759401, 1, 1, 0.529128,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.921033, 0, 1, 0.53258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467088,-99) , 
7, 0.395426, 1, 0, 0.504727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47183,-99) , 
2, -0.786982, 0, 0, 0.492682,-99) , 
7, -0.428994, 1, 0, 0.505633,-99) , 
4, 0.461597, 0, 0, 0.510699,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485464,-99) , 
11, 0.0753563, 1, 0, 0.500365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460234,-99) , 
10, -0.846154, 0, 0, 0.487286,-99) , 
7, -0.769231, 0, 0, 0.50581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479758,-99) , 
2, -0.307692, 1, 0, 0.503307,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0581953);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486356,-99) , 
4, -0.461597, 0, 0, 0.513416,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543492,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493122,-99) , 
9, -0.934568, 1, 0, 0.521773,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52953,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494114,-99) , 
11, 0.153718, 0, 0, 0.499923,-99) , 
1, -0.887834, 0, 0, 0.510208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452896,-99) , 
1, -0.913651, 0, 0, 0.491336,-99) , 
8, -0.959945, 1, 0, 0.504041,-99) , 
1, -0.862017, 0, 0, 0.509466,-99) , 
NN(
0, 
0, 
-1, -0.692308, 0, -1, 0.469118,-99) , 
8, -0.905325, 1, 0, 0.502473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442047,-99) , 
8, -0.846154, 1, 0, 0.496102,-99) , 
2, -0.769231, 1, 0, 0.50209,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0559992);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528297,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531996,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497288,-99) , 
7, -0.450619, 1, 0, 0.502636,-99) , 
10, -0.846154, 1, 0, 0.512704,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538279,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540942,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486712,-99) , 
10, -0.804734, 1, 0, 0.506846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466833,-99) , 
1, -0.933402, 0, 0, 0.497001,-99) , 
11, -0.289941, 1, 0, 0.506993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467336,-99) , 
5, -0.899662, 1, 0, 0.501022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442778,-99) , 
8, -0.905325, 1, 0, 0.4939,-99) , 
1, -0.821603, 0, 0, 0.499301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456727,-99) , 
8, -0.846154, 1, 0, 0.494456,-99) , 
2, -0.778484, 1, 0, 0.500542,-99) , 
11, 0.846154, 0, 0, 0.502281,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0552293);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499376,-99) , 
7, 0.479291, 0, 0, 0.524373,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458022,-99) , 
7, 0.337071, 1, 0, 0.491355,-99) , 
9, -0.909694, 1, 0, 0.511614,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54244,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47564,-99) , 
2, -0.587499, 1, 0, 0.498791,-99) , 
5, -0.916049, 1, 0, 0.511774,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488627,-99) , 
10, -0.804734, 1, 0, 0.502382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465993,-99) , 
4, -0.307692, 1, 0, 0.484105,-99) , 
0, -0.923077, 0, 0, 0.496065,-99) , 
7, -0.230769, 0, 0, 0.50244,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0530269);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491419,-99) , 
2, -0.61215, 1, 0, 0.525861,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47176,-99) , 
7, 0.337071, 1, 0, 0.49245,-99) , 
9, -0.909694, 1, 0, 0.512955,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544064,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.882737, 0, 1, 0.531627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484517,-99) , 
1, -0.911371, 0, 0, 0.515104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485798,-99) , 
5, -0.851173, 1, 0, 0.509588,-99) , 
7, -0.585175, 0, 0, 0.515889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477267,-99) , 
4, -0.840238, 0, 0, 0.510471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476142,-99) , 
7, -0.43787, 1, 0, 0.505023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477328,-99) , 
4, 0.384615, 1, 0, 0.498862,-99) , 
7, -0.230769, 0, 0, 0.504639,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0530345);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547072,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547309,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538928,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547577,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496729,-99) , 
0, -0.919926, 0, 0, 0.510379,-99) , 
8, -0.924156, 0, 0, 0.52198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483139,-99) , 
4, 0.0768199, 1, 0, 0.509021,-99) , 
7, 0.360947, 0, 0, 0.516148,-99) , 
NN(
0, 
0, 
-1, -0.877993, 0, -1, 0.478629,-99) , 
5, -0.876766, 1, 0, 0.508897,-99) , 
1, -0.775184, 0, 0, 0.512349,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442752,-99) , 
5, -0.934116, 1, 0, 0.474659,-99) , 
6, -0.937745, 0, 0, 0.505238,-99) , 
5, -0.955621, 1, 0, 0.50964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488193,-99) , 
5, -0.769231, 1, 0, 0.507668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490552,-99) , 
7, -0.846154, 0, 0, 0.505898,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0614242);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529996,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527187,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.692308, 1, 1, 0.533123,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475973,-99) , 
10, -0.64497, 1, 0, 0.490181,-99) , 
6, -0.884284, 1, 0, 0.514402,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545589,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484822,-99) , 
1, -0.920359, 0, 0, 0.505266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446916,-99) , 
0, -0.906201, 1, 0, 0.492822,-99) , 
10, -0.934911, 1, 0, 0.504849,-99) , 
NN(
0, 
0, 
-1, -0.919125, 0, -1, 0.445218,-99) , 
8, -0.932653, 1, 0, 0.490652,-99) , 
1, -0.880393, 0, 0, 0.500591,-99) , 
0, -0.968178, 1, 0, 0.505904,-99) , 
1, -0.692308, 0, 0, 0.507739,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0494048);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514114,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.585606, 1, 1, 0.546336,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494081,-99) , 
4, -0.466938, 0, 0, 0.509577,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472415,-99) , 
8, -0.952723, 1, 0, 0.493062,-99) , 
6, -0.914326, 0, 0, 0.500668,-99) , 
7, -0.130193, 0, 0, 0.511435,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459774,-99) , 
7, -0.43094, 1, 0, 0.489261,-99) , 
2, -0.772244, 0, 0, 0.504178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470728,-99) , 
7, 0.615385, 1, 0, 0.499293,-99) , 
4, 0.538462, 0, 0, 0.501902,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0475613);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.374255, 0, 1, 0.517511,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49092,-99) , 
5, -0.938381, 1, 0, 0.515966,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.461649, 1, 1, 0.518861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462038,-99) , 
8, -0.838116, 1, 0, 0.500327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45723,-99) , 
1, -0.878871, 0, 0, 0.485413,-99) , 
5, -0.917729, 1, 0, 0.497402,-99) , 
2, -0.791041, 1, 0, 0.504141,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486596,-99) , 
2, -0.610165, 1, 0, 0.504412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469679,-99) , 
10, -0.692308, 1, 0, 0.492111,-99) , 
11, 0.384615, 1, 0, 0.499948,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0529321);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537948,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542962,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485291,-99) , 
0, -0.874832, 0, 0, 0.511146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473153,-99) , 
8, -0.882455, 1, 0, 0.497449,-99) , 
9, -0.846154, 0, 0, 0.507378,-99) , 
5, -0.914114, 1, 0, 0.516491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47112,-99) , 
7, 0.384615, 1, 0, 0.50782,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522049,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.943559, 1, 1, 0.516107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487721,-99) , 
0, -0.95858, 0, 0, 0.502916,-99) , 
NN(
0, 
0, 
-1, -0.952314, 1, -1, 0.468804,-99) , 
4, -0.307692, 1, 0, 0.48585,-99) , 
7, 0.465531, 0, 0, 0.492913,-99) , 
0, -0.923077, 0, 0, 0.498992,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0475984);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538785,-99) , 
NN(
NN(
0, 
0, 
-1, -0.605087, 0, 1, 0.518635,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483278,-99) , 
2, -0.399525, 0, 0, 0.50716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472915,-99) , 
8, -0.92469, 1, 0, 0.49211,-99) , 
10, -0.692308, 0, 0, 0.503137,-99) , 
11, 0.692308, 0, 0, 0.507969,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515515,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482399,-99) , 
10, -0.804734, 1, 0, 0.501031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47541,-99) , 
7, -0.0687208, 1, 0, 0.491486,-99) , 
4, 0, 0, 0, 0.500429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451421,-99) , 
0, -0.931953, 1, 0, 0.495278,-99) , 
0, -0.923077, 0, 0, 0.500452,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0463713);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, -0.460404, 1, 1, 0.524929,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, -0.900551, 1, 1, 0.531917,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47424,-99) , 
11, 0.230237, 0, 0, 0.494822,-99) , 
8, -0.92366, 0, 0, 0.509269,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472765,-99) , 
11, 0.0744621, 1, 0, 0.491781,-99) , 
10, -0.633136, 1, 0, 0.501748,-99) , 
2, -0.600595, 0, 0, 0.506629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47839,-99) , 
3, -0.804683, 1, 0, 0.504425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477767,-99) , 
10, -0.923077, 0, 0, 0.501565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479456,-99) , 
2, -0.307692, 1, 0, 0.499444,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadBDT::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.00584312109277;
   fMax_1[0][0] = 3.06083631516;
   fMin_1[1][0] = 0.00168255029712;
   fMax_1[1][0] = 9.17481613159;
   fMin_1[2][0] = 0.00168255029712;
   fMax_1[2][0] = 9.17481613159;
   fMin_1[0][1] = 0.21610571444;
   fMax_1[0][1] = 15.2411336899;
   fMin_1[1][1] = 0.181815564632;
   fMax_1[1][1] = 16.2598876953;
   fMin_1[2][1] = 0.181815564632;
   fMax_1[2][1] = 16.2598876953;
   fMin_1[0][2] = 0.0236073061824;
   fMax_1[0][2] = 4.78038072586;
   fMin_1[1][2] = 0.0128279421479;
   fMax_1[1][2] = 4.71813678741;
   fMin_1[2][2] = 0.0128279421479;
   fMax_1[2][2] = 4.78038072586;
   fMin_1[0][3] = 0.0010531732114;
   fMax_1[0][3] = 1.13358068466;
   fMin_1[1][3] = 0.00240192282945;
   fMax_1[1][3] = 2.29247522354;
   fMin_1[2][3] = 0.0010531732114;
   fMax_1[2][3] = 2.29247522354;
   fMin_1[0][4] = 0.0223794020712;
   fMax_1[0][4] = 0.999228954315;
   fMin_1[1][4] = 0.0209744982421;
   fMax_1[1][4] = 0.998989284039;
   fMin_1[2][4] = 0.0209744982421;
   fMax_1[2][4] = 0.999228954315;
   fMin_1[0][5] = 0.0443222820759;
   fMax_1[0][5] = 7.5899477005;
   fMin_1[1][5] = 0.0508591905236;
   fMax_1[1][5] = 7.86185455322;
   fMin_1[2][5] = 0.0443222820759;
   fMax_1[2][5] = 7.86185455322;
   fMin_1[0][6] = -0.0110585857183;
   fMax_1[0][6] = 1.09178972244;
   fMin_1[1][6] = 0.00252036727034;
   fMax_1[1][6] = 1.23307979107;
   fMin_1[2][6] = -0.0110585857183;
   fMax_1[2][6] = 1.23307979107;
   fMin_1[0][7] = 0.0220826398581;
   fMax_1[0][7] = 0.999443650246;
   fMin_1[1][7] = 0.0138477738947;
   fMax_1[1][7] = 0.999490857124;
   fMin_1[2][7] = 0.0138477738947;
   fMax_1[2][7] = 0.999490857124;
   fMin_1[0][8] = 0.0125337867066;
   fMax_1[0][8] = 4.51049947739;
   fMin_1[1][8] = 0.00636615557596;
   fMax_1[1][8] = 6.34561729431;
   fMin_1[2][8] = 0.00636615557596;
   fMax_1[2][8] = 6.34561729431;
   fMin_1[0][9] = -0.0227187406272;
   fMax_1[0][9] = 0.567384719849;
   fMin_1[1][9] = -0.0285268686712;
   fMax_1[1][9] = 1.2399750948;
   fMin_1[2][9] = -0.0285268686712;
   fMax_1[2][9] = 1.2399750948;
   fMin_1[0][10] = 2;
   fMax_1[0][10] = 15;
   fMin_1[1][10] = 2;
   fMax_1[1][10] = 15;
   fMin_1[2][10] = 2;
   fMax_1[2][10] = 15;
   fMin_1[0][11] = 4.51555279142e-05;
   fMax_1[0][11] = 0.9667339921;
   fMin_1[1][11] = 3.40490714734e-06;
   fMax_1[1][11] = 0.967006444931;
   fMin_1[2][11] = 3.40490714734e-06;
   fMax_1[2][11] = 0.967006444931;
}

//_______________________________________________________________________
inline void ReadBDT::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadBDT::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadBDT::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
