// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : dansand
Date           : Sat Aug 13 12:11:22 2016
Host           : Linux cmsbuild17.cern.ch 2.6.32-431.29.2.el6.x86_64 #1 SMP Wed Sep 10 11:13:12 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/dansand/CMSDAS15/CMSSW_7_3_0/src/Analysis/B2GDAS/test/DESYBDT/80X/elec
Training events: 698949
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "I" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "150" [Max depth of the decision tree allowed]
MinNodeSize: "5" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "25" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
DRpt                          DRpt                          DRpt                          DRpt                                                            'F'    [0.00168255029712,8.37497615814]
ht_met_lep_norm               ht_met_lep_norm               ht_met_lep_norm               ht_met_lep_norm                                                 'F'    [0.183467686176,15.2271690369]
lep1__minDR_jet               lep1__minDR_jet               lep1__minDR_jet               lep1__minDR_jet                                                 'F'    [0.0163093730807,4.37146949768]
lep1__pTrel_jet_norm          lep1__pTrel_jet_norm          lep1__pTrel_jet_norm          lep1__pTrel_jet_norm                                            'F'    [0.000825996161439,1.9793202877]
jet1_csv                      jet1_csv                      jet1_csv                      jet1_csv                                                        'F'    [-10,0.998456716537]
jet1_m                        jet1_m                        jet1_m                        jet1_m                                                          'F'    [0.00106288958341,0.982407033443]
jet2_csv                      jet2_csv                      jet2_csv                      jet2_csv                                                        'F'    [0.0138477738947,0.999255716801]
jet2_pt                       jet2_pt                       jet2_pt                       jet2_pt                                                         'F'    [0.00984981842339,7.04766893387]
njets                         njets                         njets                         njets                                                           'I'    [2,15]
s33                           s33                           s33                           s33                                                             'F'    [8.64624689711e-06,0.967223763466]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "DRpt", "ht_met_lep_norm", "lep1__minDR_jet", "lep1__pTrel_jet_norm", "jet1_csv", "jet1_m", "jet2_csv", "jet2_pt", "njets", "s33" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0.00168255029711872;
      fVmax[0] = 8.37497615814209;
      fVmin[1] = 0.1834676861763;
      fVmax[1] = 15.2271690368652;
      fVmin[2] = 0.0163093730807304;
      fVmax[2] = 4.37146949768066;
      fVmin[3] = 0.000825996161438525;
      fVmax[3] = 1.97932028770447;
      fVmin[4] = -10;
      fVmax[4] = 0.998456716537476;
      fVmin[5] = 0.00106288958340883;
      fVmax[5] = 0.982407033443451;
      fVmin[6] = 0.0138477738946676;
      fVmax[6] = 0.99925571680069;
      fVmin[7] = 0.00984981842339039;
      fVmax[7] = 7.04766893386841;
      fVmin[8] = 2;
      fVmax[8] = 15;
      fVmin[9] = 8.64624689711491e-06;
      fVmax[9] = 0.967223763465881;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation
inline void ReadBDT::InitTransform_Identity_1() {}

inline void ReadBDT::Transform_Identity_1(const std::vector<double> &, int) const {}
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.723047910261599);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.923736,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.725354,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315761,-99) , 
8, 3.26923, 0, 0, 0.468572,-99) , 
0, 0.175094, 1, 0, 0.585686,-99) , 
6, 0.51039, 0, 0, 0.756104,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619548,-99) , 
NN(
0, 
0, 
-1, 0.575016, 0, -1, 0.146345,-99) , 
6, 0.733941, 0, 0, 0.21177,-99) , 
0, 0.323732, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.576494);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.359957, 0, 1, 0.851861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487177,-99) , 
2, 0.99406, 1, 0, 0.777847,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.722577,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535485,-99) , 
NN(
0, 
0, 
-1, 4.30769, 0, -1, 0.297946,-99) , 
6, 0.385383, 0, 0, 0.377294,-99) , 
NN(
0, 
0, 
-1, 0.604651, 1, -1, 0.139821,-99) , 
2, 0.855916, 1, 0, 0.258087,-99) , 
6, 0.809754, 0, 0, 0.33726,-99) , 
4, 0.575439, 0, 0, 0.485372,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.471215);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.858069,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433426,-99) , 
7, 0.249037, 1, 0, 0.593641,-99) , 
4, 0.835758, 0, 0, 0.731241,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69001,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525061,-99) , 
NN(
0, 
0, 
-1, 0.131407, 1, -1, 0.334607,-99) , 
8, 4.5, 0, 0, 0.397455,-99) , 
6, 0.696053, 0, 0, 0.469063,-99) , 
NN(
0, 
0, 
-1, 1.1087, 1, -1, 0.146643,-99) , 
0, 0.549823, 1, 0, 0.37334,-99) , 
4, 0.575439, 0, 0, 0.491838,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.367909);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.833877,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.699014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44036,-99) , 
4, 0.803219, 0, 0, 0.579936,-99) , 
6, 0.510371, 0, 0, 0.682924,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44679,-99) , 
7, 0.184752, 1, 0, 0.542156,-99) , 
NN(
0, 
0, 
-1, 0.802812, 1, -1, 0.296899,-99) , 
0, 0.275753, 1, 0, 0.399302,-99) , 
4, 0.575439, 0, 0, 0.491375,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.354444);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.790839,-99) , 
NN(
NN(
0, 
0, 
-1, 0.370516, 1, 1, 0.657832,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603189,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57438,-99) , 
NN(
0, 
0, 
-1, 0.79528, 0, -1, 0.441767,-99) , 
9, 0.483445, 1, 0, 0.486477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328688,-99) , 
7, 0.242391, 1, 0, 0.438422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.221688,-99) , 
8, 2.42308, 0, 0, 0.404155,-99) , 
4, 0.575439, 0, 0, 0.463119,-99) , 
5, 0.0554325, 0, 0, 0.521035,-99) , 
6, 0.847655, 0, 0, 0.566518,-99) , 
NN(
0, 
0, 
-1, 0.0791833, 0, -1, 0.271628,-99) , 
0, 0.645782, 1, 0, 0.513478,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.263329);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.738453,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490559,-99) , 
2, 0.383534, 1, 0, 0.553735,-99) , 
6, 0.51039, 0, 0, 0.631459,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.438857, 0, 1, 0.58731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422582,-99) , 
2, 1.40233, 1, 0, 0.553624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36302,-99) , 
8, 2.5, 0, 0, 0.520703,-99) , 
NN(
0, 
0, 
-1, 4.5, 0, -1, 0.314846,-99) , 
7, 0.280535, 1, 0, 0.449768,-99) , 
2, 0.518828, 1, 0, 0.505092,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.254105);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.700554,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460641,-99) , 
5, 0.0388069, 0, 0, 0.560028,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457409,-99) , 
1, 0.738107, 0, 0, 0.545607,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602392,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380601,-99) , 
7, 0.335874, 1, 0, 0.464945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378464,-99) , 
1, 1.24824, 0, 0, 0.424246,-99) , 
NN(
0, 
0, 
-1, 0.365249, 1, -1, 0.306096,-99) , 
8, 3.5, 0, 0, 0.378441,-99) , 
5, 0.0806951, 0, 0, 0.410419,-99) , 
7, 0.149127, 1, 0, 0.453231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.262295,-99) , 
0, 0.99533, 1, 0, 0.436478,-99) , 
2, 0.518828, 1, 0, 0.473089,-99) , 
6, 0.885555, 0, 0, 0.50082,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.216199);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687265,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416614,-99) , 
4, 0.738139, 0, 0, 0.506145,-99) , 
6, 0.39756, 0, 0, 0.585541,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619952,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429617,-99) , 
5, 0.0358656, 0, 0, 0.484919,-99) , 
4, 0.340766, 0, 0, 0.544637,-99) , 
NN(
0, 
0, 
-1, 3.26923, 0, -1, 0.428307,-99) , 
4, 0.16868, 0, 0, 0.500696,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409579,-99) , 
4, 0.325116, 0, 0, 0.479265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357993,-99) , 
4, 0.168675, 0, 0, 0.439175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.212308,-99) , 
2, 1.07485, 1, 0, 0.383663,-99) , 
7, 0.28408, 1, 0, 0.459707,-99) , 
4, 0.575439, 0, 0, 0.499078,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.185832);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638852,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62032,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585695,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0340618, 1, 1, 0.543757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430355,-99) , 
1, 0.836544, 0, 0, 0.501067,-99) , 
7, 0.103548, 1, 0, 0.52711,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518082,-99) , 
NN(
0, 
0, 
-1, 3.5, 0, -1, 0.372032,-99) , 
0, 0.235737, 1, 0, 0.425748,-99) , 
7, 0.197247, 1, 0, 0.479013,-99) , 
5, 0.0826173, 0, 0, 0.493049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363428,-99) , 
7, 0.551221, 1, 0, 0.47893,-99) , 
6, 0.885555, 0, 0, 0.497705,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.170019);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566653,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541528,-99) , 
NN(
0, 
0, 
-1, 0.606238, 1, -1, 0.455022,-99) , 
7, 0.222457, 1, 0, 0.49827,-99) , 
NN(
0, 
0, 
-1, 0.205064, 1, -1, 0.423421,-99) , 
6, 0.212315, 0, 0, 0.466634,-99) , 
8, 5.5, 0, 0, 0.487002,-99) , 
6, 0.848812, 0, 0, 0.510748,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567712,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432438,-99) , 
0, 0.486869, 1, 0, 0.495554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29083,-99) , 
7, 0.210734, 1, 0, 0.409876,-99) , 
2, 1.18885, 1, 0, 0.488771,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.177711);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634748,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634222,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567453,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551386,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513201,-99) , 
NN(
0, 
0, 
-1, 0.0460726, 0, -1, 0.433731,-99) , 
0, 0.147826, 1, 0, 0.460546,-99) , 
2, 0.996037, 0, 0, 0.47655,-99) , 
9, 0.26042, 1, 0, 0.494038,-99) , 
6, 0.771854, 0, 0, 0.520672,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43696,-99) , 
1, 1.40297, 0, 0, 0.49059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362722,-99) , 
8, 3.38462, 0, 0, 0.431658,-99) , 
0, 0.423875, 1, 0, 0.498396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320389,-99) , 
7, 0.467684, 1, 0, 0.480255,-99) , 
5, 0.114295, 0, 0, 0.491741,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.138952);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639469,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423678,-99) , 
5, 0.0412759, 0, 0, 0.488876,-99) , 
4, 0.884568, 0, 0, 0.541505,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558951,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527742,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479317,-99) , 
0, 0.341946, 1, 0, 0.513934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475897,-99) , 
8, 4.38462, 1, 0, 0.49601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425133,-99) , 
7, 0.416443, 1, 0, 0.484258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43876,-99) , 
1, 0.912251, 0, 0, 0.473345,-99) , 
7, 0.117254, 1, 0, 0.483542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379445,-99) , 
8, 2.5, 0, 0, 0.469813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322884,-99) , 
0, 0.732097, 1, 0, 0.455035,-99) , 
5, 0.0992739, 0, 0, 0.464756,-99) , 
4, 0.575439, 0, 0, 0.488386,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.108808);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.0385815, 0, 1, 0.554359,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493904,-99) , 
6, 0.247213, 0, 0, 0.534166,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524972,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512672,-99) , 
NN(
0, 
0, 
-1, 0.691679, 0, -1, 0.474808,-99) , 
0, 0.265293, 1, 0, 0.493683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407182,-99) , 
7, 0.382925, 1, 0, 0.476489,-99) , 
8, 5.30769, 0, 0, 0.489184,-99) , 
9, 0.371601, 1, 0, 0.504009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406691,-99) , 
8, 2.5, 0, 0, 0.494187,-99) , 
7, 0.151414, 1, 0, 0.509513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411915,-99) , 
1, 0.648272, 0, 0, 0.500608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348508,-99) , 
0, 0.967832, 1, 0, 0.491068,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.118229);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604338,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525762,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453335,-99) , 
9, 0.557653, 1, 0, 0.489199,-99) , 
4, 0.868298, 0, 0, 0.533475,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585574,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473226,-99) , 
5, 0.0476451, 0, 0, 0.511254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457425,-99) , 
4, 0.250513, 0, 0, 0.488405,-99) , 
4, 0.434631, 0, 0, 0.51334,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428894,-99) , 
2, 0.797779, 0, 0, 0.460532,-99) , 
4, 0.16868, 0, 0, 0.494968,-99) , 
NN(
0, 
0, 
-1, 0.0771401, 0, -1, 0.437678,-99) , 
5, 0.0277602, 0, 0, 0.4799,-99) , 
4, 0.575439, 0, 0, 0.496471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373602,-99) , 
0, 0.967832, 1, 0, 0.488847,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.102848);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608015,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476493,-99) , 
5, 0.0805265, 0, 0, 0.512025,-99) , 
1, 1.03081, 1, 0, 0.541157,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.46154, 1, 1, 0.553893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49696,-99) , 
5, 0.0369069, 1, 0, 0.53341,-99) , 
NN(
0, 
0, 
-1, 0.248612, 0, -1, 0.469896,-99) , 
3, 0.0564901, 0, 0, 0.505694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43673,-99) , 
0, 0.573263, 1, 0, 0.498534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422394,-99) , 
8, 2.5, 0, 0, 0.486654,-99) , 
5, 0.0554325, 0, 0, 0.502141,-99) , 
NN(
0, 
0, 
-1, 2.82787, 0, -1, 0.41493,-99) , 
7, 0.551221, 1, 0, 0.493014,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0873748);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582189,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577471,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497111,-99) , 
1, 1.08115, 1, 0, 0.518181,-99) , 
9, 0.334616, 1, 0, 0.537457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47678,-99) , 
6, 0.134435, 0, 0, 0.52425,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517155,-99) , 
NN(
0, 
0, 
-1, 0.183941, 1, -1, 0.445214,-99) , 
0, 0.22464, 1, 0, 0.480531,-99) , 
5, 0.0388675, 0, 0, 0.505044,-99) , 
4, 0.868298, 0, 0, 0.51674,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480098,-99) , 
1, 1.39563, 0, 0, 0.492593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438788,-99) , 
8, 3.38462, 0, 0, 0.472654,-99) , 
4, 0.152422, 0, 0, 0.507004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417032,-99) , 
0, 0.967832, 1, 0, 0.501526,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.107311);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580778,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559708,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604245,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492561,-99) , 
0, 0.367337, 1, 0, 0.526884,-99) , 
2, 1.80242, 0, 0, 0.548043,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424702,-99) , 
1, 1.27969, 0, 0, 0.48773,-99) , 
7, 0.203546, 1, 0, 0.525012,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508971,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46079,-99) , 
5, 0.0313639, 1, 0, 0.491077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420916,-99) , 
3, 0.0373065, 0, 0, 0.464949,-99) , 
5, 0.0489674, 0, 0, 0.481514,-99) , 
2, 0.855916, 0, 0, 0.499508,-99) , 
6, 0.847655, 0, 0, 0.507619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401016,-99) , 
7, 0.467684, 1, 0, 0.497145,-99) , 
5, 0.114295, 0, 0, 0.503359,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.087796);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56129,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543643,-99) , 
NN(
NN(
0, 
0, 
-1, 0.252936, 0, 1, 0.520294,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482471,-99) , 
8, 3.07692, 0, 0, 0.526359,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442116,-99) , 
6, 0.174127, 0, 0, 0.494604,-99) , 
2, 0.807796, 0, 0, 0.507729,-99) , 
NN(
0, 
0, 
-1, 4.15385, 0, -1, 0.458494,-99) , 
7, 0.367658, 1, 0, 0.496321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385716,-99) , 
1, 0.778914, 0, 0, 0.483687,-99) , 
7, 0.134035, 1, 0, 0.493062,-99) , 
9, 0.148819, 1, 0, 0.498747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405569,-99) , 
0, 0.890274, 1, 0, 0.492082,-99) , 
8, 6.5, 0, 0, 0.497618,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.104847);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559776,-99) , 
NN(
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.460559, 1, 1, 0.571058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492966,-99) , 
8, 3.42308, 0, 0, 0.548125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468499,-99) , 
6, 0.506532, 1, 0, 0.524374,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565149,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464402,-99) , 
2, 0.572839, 0, 0, 0.483716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417182,-99) , 
8, 4.38462, 1, 0, 0.458629,-99) , 
6, 0.660786, 0, 0, 0.484585,-99) , 
0, 0.324927, 0, 0, 0.499117,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406883,-99) , 
0, 0.299943, 1, 0, 0.459942,-99) , 
8, 2.5, 0, 0, 0.493962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401333,-99) , 
0, 0.765718, 1, 0, 0.486333,-99) , 
5, 0.114295, 0, 0, 0.491781,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.089046);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559499,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544305,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496575,-99) , 
6, 0.287177, 0, 0, 0.521873,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538932,-99) , 
NN(
0, 
0, 
-1, 1.15974, 0, -1, 0.457316,-99) , 
2, 0.858171, 0, 0, 0.491511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425325,-99) , 
0, 0.534114, 1, 0, 0.480276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422505,-99) , 
1, 0.816907, 0, 0, 0.471841,-99) , 
0, 0.193949, 1, 0, 0.490802,-99) , 
1, 1.70828, 0, 0, 0.499063,-99) , 
NN(
0, 
0, 
-1, 0.359194, 1, -1, 0.457408,-99) , 
7, 0.553714, 1, 0, 0.494074,-99) , 
NN(
0, 
0, 
-1, 0.0540266, 0, -1, 0.44237,-99) , 
8, 2.5, 0, 0, 0.488449,-99) , 
2, 2.02638, 0, 0, 0.492225,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0917448);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568959,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569463,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461342,-99) , 
2, 0.99406, 0, 0, 0.481872,-99) , 
4, 0.570433, 1, 0, 0.507584,-99) , 
6, 0.660786, 0, 0, 0.52181,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 4.5, 0, 1, 0.52445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462194,-99) , 
0, 0.274775, 0, 0, 0.497516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429376,-99) , 
6, 0.623145, 1, 0, 0.480104,-99) , 
4, 0.412741, 0, 0, 0.50335,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464384,-99) , 
0, 0.317254, 0, 0, 0.48632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429749,-99) , 
7, 0.286567, 1, 0, 0.46925,-99) , 
4, 0.152422, 0, 0, 0.495845,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.103259);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563823,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550029,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475711,-99) , 
0, 0.205533, 1, 0, 0.509398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452145,-99) , 
2, 0.37709, 0, 0, 0.48566,-99) , 
6, 0.623205, 0, 0, 0.503874,-99) , 
0, 0.334472, 0, 0, 0.515042,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552799,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529995,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447287,-99) , 
8, 4.30769, 0, 0, 0.494363,-99) , 
0, 0.418068, 1, 0, 0.509876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46605,-99) , 
1, 0.78364, 0, 0, 0.500521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44967,-99) , 
3, 0.229114, 1, 0, 0.492181,-99) , 
6, 0.512366, 0, 0, 0.500468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391597,-99) , 
6, 0.733941, 1, 0, 0.480894,-99) , 
2, 0.686334, 1, 0, 0.497101,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0784949);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0801327, 1, 1, 0.536656,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534002,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49916,-99) , 
6, 0.182409, 0, 0, 0.525484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445619,-99) , 
6, 0.398894, 1, 0, 0.488964,-99) , 
4, 0.575089, 0, 0, 0.504186,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530171,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52432,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.574687, 1, 1, 0.51726,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4597,-99) , 
7, 0.172252, 1, 0, 0.49264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455452,-99) , 
7, 0.286669, 1, 0, 0.481646,-99) , 
6, 0.487269, 0, 0, 0.488322,-99) , 
9, 0.840866, 0, 0, 0.495604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410881,-99) , 
6, 0.733941, 1, 0, 0.480437,-99) , 
2, 0.688509, 1, 0, 0.491555,-99) , 
9, 0.148811, 1, 0, 0.496648,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0713625);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534663,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.415777, 0, 1, 0.523727,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532413,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494315,-99) , 
5, 0.0673477, 1, 0, 0.515098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48338,-99) , 
6, 0.398784, 1, 0, 0.50243,-99) , 
NN(
0, 
0, 
-1, 0.362783, 1, -1, 0.437298,-99) , 
1, 1.09522, 0, 0, 0.475748,-99) , 
2, 1.46151, 0, 0, 0.486069,-99) , 
0, 0.240918, 1, 0, 0.500933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444298,-99) , 
1, 0.648272, 0, 0, 0.495316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435637,-99) , 
0, 0.890274, 1, 0, 0.491134,-99) , 
8, 6.5, 0, 0, 0.494609,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0841271);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529447,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573537,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559688,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522225,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418359,-99) , 
1, 1.54581, 0, 0, 0.465098,-99) , 
2, 1.27777, 0, 0, 0.490352,-99) , 
0, 0.394836, 1, 0, 0.510047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431455,-99) , 
0, 0.785904, 1, 0, 0.496114,-99) , 
5, 0.116374, 0, 0, 0.506764,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469837,-99) , 
8, 3.38462, 1, 0, 0.49085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444577,-99) , 
6, 0.387065, 1, 0, 0.473291,-99) , 
0, 0.323732, 0, 0, 0.48863,-99) , 
6, 0.885555, 0, 0, 0.492949,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0819921);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572174,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472741,-99) , 
0, 0.310709, 0, 0, 0.492278,-99) , 
3, 0.036211, 1, 0, 0.519749,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478638,-99) , 
1, 2.19711, 0, 0, 0.498663,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42688,-99) , 
7, 0.225504, 1, 0, 0.465095,-99) , 
8, 4.5, 0, 0, 0.48152,-99) , 
3, 0.0800408, 1, 0, 0.501323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535483,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463714,-99) , 
1, 0.992351, 1, 0, 0.505303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45554,-99) , 
7, 0.249762, 1, 0, 0.486398,-99) , 
NN(
0, 
0, 
-1, 0.151172, 1, -1, 0.431127,-99) , 
1, 0.881078, 0, 0, 0.463314,-99) , 
0, 0.144253, 1, 0, 0.480881,-99) , 
5, 0.0388069, 0, 0, 0.492382,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0741246);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531997,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.273448, 0, 1, 0.525329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481161,-99) , 
7, 0.427916, 1, 0, 0.516971,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529905,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541226,-99) , 
NN(
0, 
0, 
-1, 0.270025, 1, -1, 0.475915,-99) , 
2, 1.38951, 0, 0, 0.489155,-99) , 
6, 0.582343, 0, 0, 0.500603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418115,-99) , 
1, 0.671513, 0, 0, 0.489169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391723,-99) , 
7, 0.270657, 1, 0, 0.476368,-99) , 
1, 1.15983, 0, 0, 0.492323,-99) , 
7, 0.0931374, 1, 0, 0.496971,-99) , 
NN(
0, 
0, 
-1, 0.359194, 1, -1, 0.457215,-99) , 
7, 0.551221, 1, 0, 0.492889,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0658885);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536674,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567646,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517534,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432734,-99) , 
8, 3.34615, 1, 0, 0.472006,-99) , 
0, 0.224637, 1, 0, 0.497228,-99) , 
1, 1.24288, 0, 0, 0.513315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475445,-99) , 
5, 0.0554325, 1, 0, 0.5018,-99) , 
0, 0.645782, 0, 0, 0.506625,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499608,-99) , 
6, 0.752878, 0, 0, 0.502233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450885,-99) , 
8, 3.46154, 0, 0, 0.486294,-99) , 
6, 0.506534, 1, 0, 0.499954,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420202,-99) , 
5, 0.0369999, 0, 0, 0.467019,-99) , 
8, 2.5, 0, 0, 0.495996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456238,-99) , 
3, 0.229114, 1, 0, 0.492459,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0644363);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.5, 1, 1, 0.523634,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.249993, 0, 1, 0.52844,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488267,-99) , 
3, 0.159982, 1, 0, 0.514139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458326,-99) , 
8, 3.5, 0, 0, 0.496918,-99) , 
0, 0.369666, 1, 0, 0.509823,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426253,-99) , 
7, 0.122002, 1, 0, 0.471632,-99) , 
1, 0.775907, 0, 0, 0.503068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470335,-99) , 
2, 0.351322, 0, 0, 0.498009,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427302,-99) , 
7, 0.222802, 1, 0, 0.47373,-99) , 
6, 0.696053, 1, 0, 0.492874,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.071447);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555361,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465161,-99) , 
9, 0.594852, 1, 0, 0.493573,-99) , 
3, 0.036211, 1, 0, 0.514775,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488508,-99) , 
1, 2.19711, 0, 0, 0.500949,-99) , 
NN(
0, 
0, 
-1, 0.483683, 1, -1, 0.464648,-99) , 
8, 4.5, 0, 0, 0.482451,-99) , 
3, 0.0800408, 1, 0, 0.499196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52823,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494835,-99) , 
0, 0.404583, 1, 0, 0.524342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471892,-99) , 
2, 0.779676, 0, 0, 0.50127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429674,-99) , 
1, 0.613798, 0, 0, 0.486083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391012,-99) , 
7, 0.229749, 1, 0, 0.470205,-99) , 
1, 1.20061, 0, 0, 0.480085,-99) , 
5, 0.0388069, 0, 0, 0.490844,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0668456);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538719,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528615,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485058,-99) , 
3, 0.0388101, 0, 0, 0.514618,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537861,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467527,-99) , 
1, 1.16644, 0, 0, 0.4902,-99) , 
3, 0.0427749, 1, 0, 0.503199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465083,-99) , 
0, 0.480965, 1, 0, 0.49439,-99) , 
NN(
0, 
0, 
-1, 0.877001, 0, -1, 0.450297,-99) , 
5, 0.0332894, 0, 0, 0.482329,-99) , 
0, 0.165647, 1, 0, 0.492044,-99) , 
5, 0.114295, 0, 0, 0.495176,-99) , 
NN(
0, 
0, 
-1, 0.178601, 1, -1, 0.462371,-99) , 
2, 1.25327, 1, 0, 0.490463,-99) , 
2, 2.02638, 0, 0, 0.493022,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0642256);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519497,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585349,-99) , 
NN(
NN(
0, 
0, 
-1, 1.42126, 0, 1, 0.530502,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466701,-99) , 
1, 1.2692, 0, 0, 0.489571,-99) , 
7, 0.176425, 1, 0, 0.510617,-99) , 
6, 0.42928, 0, 0, 0.524726,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519807,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452452,-99) , 
7, 0.282378, 0, 0, 0.473636,-99) , 
3, 0.0465715, 1, 0, 0.489059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451359,-99) , 
5, 0.0316301, 0, 0, 0.480434,-99) , 
2, 0.884852, 0, 0, 0.501288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462664,-99) , 
6, 0.733941, 1, 0, 0.494131,-99) , 
0, 0.142413, 1, 0, 0.498938,-99) , 
NN(
0, 
0, 
-1, 0.359194, 1, -1, 0.466383,-99) , 
7, 0.551221, 1, 0, 0.495598,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0462668);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520645,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520631,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520281,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470917,-99) , 
2, 1.25056, 0, 0, 0.491286,-99) , 
0, 0.262781, 1, 0, 0.50682,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489522,-99) , 
3, 0.0738463, 0, 0, 0.498961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443249,-99) , 
2, 0.892469, 1, 0, 0.48447,-99) , 
7, 0.286185, 1, 0, 0.498026,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472487,-99) , 
2, 0.698996, 0, 0, 0.484377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452957,-99) , 
2, 1.19424, 1, 0, 0.477635,-99) , 
9, 0.664721, 1, 0, 0.491635,-99) , 
9, 0.868499, 0, 0, 0.49447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469429,-99) , 
6, 0.0896484, 0, 0, 0.491927,-99) , 
9, 0.11161, 1, 0, 0.494233,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.055089);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532684,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536682,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479812,-99) , 
4, 0.542125, 1, 0, 0.500581,-99) , 
5, 0.0772416, 0, 0, 0.513399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483079,-99) , 
4, 0.262556, 0, 0, 0.505286,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47377,-99) , 
1, 0.925253, 0, 0, 0.495779,-99) , 
NN(
0, 
0, 
-1, 0.0359428, 0, -1, 0.453694,-99) , 
3, 0.0660429, 0, 0, 0.474566,-99) , 
5, 0.0410343, 0, 0, 0.491456,-99) , 
4, 0.868298, 0, 0, 0.497487,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477505,-99) , 
6, 0.203346, 0, 0, 0.494202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458396,-99) , 
2, 0.690061, 0, 0, 0.479968,-99) , 
4, 0.152422, 0, 0, 0.493621,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0577637);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.0328083, 1, 1, 0.568554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485246,-99) , 
0, 0.499132, 1, 0, 0.536744,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48204,-99) , 
0, 0.19222, 1, 0, 0.498176,-99) , 
2, 0.7776, 0, 0, 0.51736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473263,-99) , 
1, 0.681948, 0, 0, 0.509008,-99) , 
NN(
0, 
0, 
-1, 0.189918, 0, -1, 0.476036,-99) , 
8, 4.5, 1, 0, 0.499802,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494573,-99) , 
7, 0.401054, 1, 0, 0.518652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487727,-99) , 
5, 0.0787044, 1, 0, 0.505362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472027,-99) , 
6, 0.623037, 1, 0, 0.496837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42036,-99) , 
1, 1.16271, 0, 0, 0.485036,-99) , 
7, 0.280535, 1, 0, 0.494713,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0623483);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499668,-99) , 
7, 0.561377, 1, 0, 0.528124,-99) , 
NN(
NN(
0, 
0, 
-1, 0.705818, 1, 1, 0.521288,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531733,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485827,-99) , 
0, 0.500499, 1, 0, 0.513556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438315,-99) , 
2, 0.970374, 0, 0, 0.486785,-99) , 
1, 1.47889, 0, 0, 0.496377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431236,-99) , 
6, 0.696041, 1, 0, 0.483476,-99) , 
0, 0.23005, 1, 0, 0.496461,-99) , 
5, 0.0673243, 0, 0, 0.503585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48494,-99) , 
2, 0.351322, 0, 0, 0.500635,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0576966);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535524,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526033,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55589,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492736,-99) , 
4, 0.30946, 0, 0, 0.523216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494151,-99) , 
4, 0.168663, 0, 0, 0.513297,-99) , 
6, 0.243786, 0, 0, 0.524835,-99) , 
NN(
0, 
0, 
-1, 0.0350035, 0, -1, 0.48414,-99) , 
2, 0.945414, 1, 0, 0.511022,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454722,-99) , 
2, 0.86926, 0, 0, 0.482553,-99) , 
6, 0.382639, 1, 0, 0.500699,-99) , 
NN(
0, 
0, 
-1, 0.689329, 0, -1, 0.480875,-99) , 
4, 0.575439, 1, 0, 0.494619,-99) , 
6, 0.885555, 0, 0, 0.497938,-99) , 
2, 2.02638, 0, 0, 0.499932,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0795874);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537619,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562548,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471063,-99) , 
6, 0.284632, 0, 0, 0.492363,-99) , 
1, 1.40745, 1, 0, 0.520398,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539222,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54015,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476233,-99) , 
0, 0.318365, 1, 0, 0.529362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475187,-99) , 
8, 3.26923, 1, 0, 0.501546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455134,-99) , 
2, 0.666589, 0, 0, 0.484206,-99) , 
1, 1.30664, 0, 0, 0.494379,-99) , 
0, 0.1251, 1, 0, 0.503648,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442769,-99) , 
7, 0.171322, 1, 0, 0.473089,-99) , 
0, 0.460089, 1, 0, 0.497181,-99) , 
5, 0.0640587, 0, 0, 0.502379,-99) , 
1, 3.07649, 0, 0, 0.504301,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.063214);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565823,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536652,-99) , 
NN(
NN(
0, 
0, 
-1, 0.520581, 1, 1, 0.526214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477504,-99) , 
2, 1.11757, 0, 0, 0.507358,-99) , 
1, 1.96406, 0, 0, 0.515432,-99) , 
6, 0.486142, 0, 0, 0.522712,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.249754, 1, 1, 0.531744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475791,-99) , 
0, 0.175774, 0, 0, 0.506401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465254,-99) , 
8, 4.5, 1, 0, 0.492432,-99) , 
0, 0.323732, 0, 0, 0.506434,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440862,-99) , 
2, 0.855141, 1, 0, 0.49016,-99) , 
6, 0.696053, 1, 0, 0.50301,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0662702);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.131407, 0, 1, 0.530778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462223,-99) , 
0, 0.647599, 1, 0, 0.520361,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465848,-99) , 
0, 0.549823, 0, 0, 0.496809,-99) , 
8, 4.5, 1, 0, 0.511403,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475964,-99) , 
2, 0.99406, 0, 0, 0.490385,-99) , 
4, 0.575439, 1, 0, 0.504999,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454959,-99) , 
7, 0.222802, 1, 0, 0.485063,-99) , 
6, 0.696053, 1, 0, 0.500804,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0797221);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541959,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545167,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474668,-99) , 
0, 0.439366, 1, 0, 0.508025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469576,-99) , 
0, 0.325917, 0, 0, 0.487229,-99) , 
0, 0.183955, 1, 0, 0.507783,-99) , 
0, 0.594077, 0, 0, 0.51318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470643,-99) , 
2, 1.28623, 1, 0, 0.50745,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57819,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46252,-99) , 
5, 0.0421763, 0, 0, 0.495465,-99) , 
2, 0.829344, 0, 0, 0.515516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455663,-99) , 
0, 0.425818, 1, 0, 0.496963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435006,-99) , 
1, 0.639862, 0, 0, 0.48835,-99) , 
8, 3.5, 0, 0, 0.500341,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0511319);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563826,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548413,-99) , 
NN(
NN(
0, 
0, 
-1, 0.389973, 1, 1, 0.517479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456967,-99) , 
1, 0.982092, 0, 0, 0.502378,-99) , 
0, 0.253665, 1, 0, 0.516685,-99) , 
2, 1.26537, 0, 0, 0.524898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494823,-99) , 
0, 0.696646, 1, 0, 0.518694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484223,-99) , 
2, 0.468338, 0, 0, 0.509794,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462848,-99) , 
7, 0.120923, 1, 0, 0.487645,-99) , 
1, 0.775907, 0, 0, 0.506104,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463302,-99) , 
6, 0.894302, 0, 0, 0.485925,-99) , 
6, 0.696053, 1, 0, 0.501856,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0703284);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492706,-99) , 
6, 0.359957, 0, 0, 0.52991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468503,-99) , 
4, 0.689329, 0, 0, 0.514256,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56859,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522109,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477517,-99) , 
5, 0.0267757, 0, 0, 0.511179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481465,-99) , 
5, 0.046822, 1, 0, 0.499412,-99) , 
0, 0.547867, 0, 0, 0.504774,-99) , 
4, 0.481565, 0, 0, 0.51525,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467364,-99) , 
7, 0.150703, 0, 0, 0.504285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48071,-99) , 
7, 0.285938, 1, 0, 0.497377,-99) , 
4, 0.168683, 0, 0, 0.508747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450263,-99) , 
6, 0.696053, 1, 0, 0.496315,-99) , 
4, 0.575439, 0, 0, 0.501752,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0655179);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550065,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481547,-99) , 
7, 0.243098, 0, 0, 0.505342,-99) , 
4, 0.884568, 0, 0, 0.520541,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58287,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49997,-99) , 
9, 0.52025, 0, 0, 0.511056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485322,-99) , 
5, 0.0349152, 0, 0, 0.499365,-99) , 
6, 0.442411, 0, 0, 0.517667,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.168655, 0, 1, 0.532021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498675,-99) , 
6, 0.105578, 0, 0, 0.523773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454857,-99) , 
6, 0.385383, 1, 0, 0.499219,-99) , 
2, 0.855916, 0, 0, 0.506782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457684,-99) , 
6, 0.809754, 1, 0, 0.499359,-99) , 
4, 0.575439, 0, 0, 0.505777,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0455472);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496274,-99) , 
7, 0.243098, 1, 0, 0.516243,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559571,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489052,-99) , 
6, 0.143358, 1, 0, 0.503093,-99) , 
6, 0.350576, 0, 0, 0.519772,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 1.24808, 0, 1, 0.522049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496366,-99) , 
9, 0.706837, 1, 0, 0.515524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471146,-99) , 
6, 0.385383, 1, 0, 0.499726,-99) , 
2, 0.855916, 0, 0, 0.507945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473985,-99) , 
6, 0.809754, 1, 0, 0.502814,-99) , 
4, 0.575439, 0, 0, 0.506883,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0481069);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.0308486, 1, 1, 0.527289,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498606,-99) , 
0, 0.666674, 1, 0, 0.5168,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45414,-99) , 
1, 1.87521, 0, 0, 0.488949,-99) , 
2, 1.0131, 0, 0, 0.504606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469784,-99) , 
6, 0.696023, 1, 0, 0.497806,-99) , 
0, 0.358332, 1, 0, 0.512225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490553,-99) , 
2, 0.317662, 0, 0, 0.509244,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454118,-99) , 
7, 0.131894, 1, 0, 0.494587,-99) , 
1, 0.762072, 0, 0, 0.506937,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0514585);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530816,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527724,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531298,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482768,-99) , 
8, 4.38462, 0, 0, 0.508703,-99) , 
5, 0.035, 1, 0, 0.516042,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510192,-99) , 
NN(
0, 
0, 
-1, 1.69607, 0, -1, 0.471347,-99) , 
3, 0.0703761, 1, 0, 0.490304,-99) , 
6, 0.188764, 1, 0, 0.503023,-99) , 
6, 0.582331, 0, 0, 0.509666,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.884781, 0, 1, 0.517808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476798,-99) , 
3, 0.0382166, 0, 0, 0.503161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437255,-99) , 
0, 0.423803, 1, 0, 0.489207,-99) , 
8, 3.5, 0, 0, 0.502465,-99) , 
2, 2.02638, 0, 0, 0.503972,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0434179);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523563,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532879,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444403,-99) , 
2, 1.16245, 0, 0, 0.479699,-99) , 
5, 0.0805752, 0, 0, 0.496789,-99) , 
0, 0.301397, 1, 0, 0.509319,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527324,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.623658, 0, 1, 0.513069,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509433,-99) , 
NN(
0, 
0, 
-1, 0.782922, 0, -1, 0.483586,-99) , 
6, 0.435083, 0, 0, 0.493942,-99) , 
5, 0.0311903, 1, 0, 0.499072,-99) , 
NN(
0, 
0, 
-1, 0.643015, 0, -1, 0.484571,-99) , 
3, 0.154232, 1, 0, 0.496209,-99) , 
9, 0.875302, 0, 0, 0.499167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467688,-99) , 
1, 0.658884, 0, 0, 0.495122,-99) , 
9, 0.372014, 1, 0, 0.499722,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0432384);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.81073, 1, 1, 0.515678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474571,-99) , 
4, 0.673059, 0, 0, 0.50656,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497047,-99) , 
8, 4.5, 0, 0, 0.525173,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522935,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481479,-99) , 
9, 0.520497, 0, 0, 0.494062,-99) , 
3, 0.0520238, 1, 0, 0.50685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477139,-99) , 
8, 4.5, 1, 0, 0.494931,-99) , 
0, 0.55647, 0, 0, 0.503663,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467025,-99) , 
7, 0.12809, 0, 0, 0.492506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461108,-99) , 
6, 0.392851, 1, 0, 0.47963,-99) , 
5, 0.0337999, 0, 0, 0.494956,-99) , 
4, 0.575439, 0, 0, 0.498468,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0486824);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520232,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.931069, 0, 1, 0.528829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496911,-99) , 
7, 0.559441, 1, 0, 0.518335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488973,-99) , 
5, 0.0411322, 0, 0, 0.511664,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46781,-99) , 
0, 0.175094, 1, 0, 0.494405,-99) , 
0, 0.323732, 0, 0, 0.50244,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.334574, 0, 1, 0.515122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480738,-99) , 
6, 0.522748, 1, 0, 0.49855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455058,-99) , 
6, 0.173306, 0, 0, 0.48569,-99) , 
8, 3.5, 0, 0, 0.49655,-99) , 
2, 2.02638, 0, 0, 0.497809,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }
inline void ReadBDT::InitTransform_Identity_1() {}

inline void ReadBDT::Transform_Identity_1(const std::vector<double> &, int) const {}

//_______________________________________________________________________
inline void ReadBDT::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadBDT::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
