// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : dansand
Date           : Sat Aug 13 15:47:47 2016
Host           : Linux cmsbuild17.cern.ch 2.6.32-431.29.2.el6.x86_64 #1 SMP Wed Sep 10 11:13:12 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/dansand/CMSDAS15/CMSSW_7_3_0/src/Analysis/B2GDAS/test/DESYBDT/80X/muon
Training events: 1076655
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "I" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "150" [Max depth of the decision tree allowed]
MinNodeSize: "5" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "25" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
DRpt                          DRpt                          DRpt                          DRpt                                                            'F'    [0.00409078644589,8.82204818726]
ht_met_lep_norm               ht_met_lep_norm               ht_met_lep_norm               ht_met_lep_norm                                                 'F'    [0.182331368327,16.2846679688]
lep1__minDR_jet               lep1__minDR_jet               lep1__minDR_jet               lep1__minDR_jet                                                 'F'    [0.0177594367415,4.78038072586]
lep1__pTrel_jet_norm          lep1__pTrel_jet_norm          lep1__pTrel_jet_norm          lep1__pTrel_jet_norm                                            'F'    [4.15890172007e-05,2.29247522354]
jet1_csv                      jet1_csv                      jet1_csv                      jet1_csv                                                        'F'    [-10,0.999224603176]
jet1_m                        jet1_m                        jet1_m                        jet1_m                                                          'F'    [-0.00755744660273,1.29759728909]
jet2_csv                      jet2_csv                      jet2_csv                      jet2_csv                                                        'F'    [0.0213178601116,0.999634325504]
jet2_pt                       jet2_pt                       jet2_pt                       jet2_pt                                                         'F'    [0.00807069242001,6.52024745941]
njets                         njets                         njets                         njets                                                           'I'    [2,15]
s33                           s33                           s33                           s33                                                             'F'    [1.652926926e-06,0.96717530489]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "DRpt", "ht_met_lep_norm", "lep1__minDR_jet", "lep1__pTrel_jet_norm", "jet1_csv", "jet1_m", "jet2_csv", "jet2_pt", "njets", "s33" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0.0040907864458859;
      fVmax[0] = 8.82204818725586;
      fVmin[1] = 0.182331368327141;
      fVmax[1] = 16.28466796875;
      fVmin[2] = 0.0177594367414713;
      fVmax[2] = 4.7803807258606;
      fVmin[3] = 4.15890172007494e-05;
      fVmax[3] = 2.29247522354126;
      fVmin[4] = -10;
      fVmax[4] = 0.999224603176117;
      fVmin[5] = -0.00755744660273194;
      fVmax[5] = 1.29759728908539;
      fVmin[6] = 0.0213178601115942;
      fVmax[6] = 0.999634325504303;
      fVmin[7] = 0.0080706924200058;
      fVmax[7] = 6.52024745941162;
      fVmin[8] = 2;
      fVmax[8] = 15;
      fVmin[9] = 1.65292692599905e-06;
      fVmax[9] = 0.967175304889679;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation
inline void ReadBDT::InitTransform_Identity_1() {}

inline void ReadBDT::Transform_Identity_1(const std::vector<double> &, int) const {}
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.710775073624407);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.92047,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.717471,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304592,-99) , 
8, 3.26923, 0, 0, 0.446585,-99) , 
0, 0.174543, 1, 0, 0.565744,-99) , 
6, 0.511146, 0, 0, 0.742085,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564784,-99) , 
NN(
0, 
0, 
-1, 0.576042, 0, -1, 0.133806,-99) , 
6, 0.698614, 0, 0, 0.195213,-99) , 
0, 0.343243, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.567632);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.344928, 1, 1, 0.777925,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509191,-99) , 
NN(
0, 
0, 
-1, 0.364636, 1, -1, 0.2025,-99) , 
2, 0.379327, 1, 0, 0.244782,-99) , 
6, 0.773942, 0, 0, 0.327264,-99) , 
4, 0.576177, 0, 0, 0.478509,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.493692);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.845872,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690564,-99) , 
NN(
0, 
0, 
-1, 0.207284, 1, -1, 0.380067,-99) , 
4, 0.576177, 0, 0, 0.485929,-99) , 
6, 0.623833, 0, 0, 0.611441,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406232,-99) , 
0, 0.44358, 1, 0, 0.486559,-99) , 
NN(
0, 
0, 
-1, 0.456126, 1, -1, 0.254558,-99) , 
8, 3.5, 0, 0, 0.382611,-99) , 
NN(
0, 
0, 
-1, 1.08352, 1, -1, 0.137511,-99) , 
0, 0.669351, 1, 0, 0.279165,-99) , 
0, 0.343243, 1, 0, 0.464557,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.354875);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.783101,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444446,-99) , 
2, 0.97827, 1, 0, 0.540969,-99) , 
0, 0.238888, 1, 0, 0.672249,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468549,-99) , 
1, 0.803079, 0, 0, 0.566287,-99) , 
NN(
0, 
0, 
-1, 4.5, 0, -1, 0.381648,-99) , 
7, 0.168314, 1, 0, 0.455471,-99) , 
6, 0.398468, 0, 0, 0.551151,-99) , 
NN(
0, 
0, 
-1, 1.08352, 1, -1, 0.20329,-99) , 
0, 0.682395, 1, 0, 0.493103,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.319616);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.820243, 0, 1, 0.679106,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.684165,-99) , 
NN(
NN(
0, 
0, 
-1, 0.17018, 1, 1, 0.592295,-99) , 
NN(
0, 
0, 
-1, 0.183077, 1, -1, 0.439879,-99) , 
0, 0.266182, 1, 0, 0.531159,-99) , 
5, 0.0536585, 0, 0, 0.564784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387156,-99) , 
7, 0.33012, 1, 0, 0.525637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296165,-99) , 
8, 2.5, 0, 0, 0.491481,-99) , 
4, 0.576177, 0, 0, 0.555178,-99) , 
NN(
0, 
0, 
-1, 1.08352, 1, -1, 0.266787,-99) , 
0, 0.682395, 1, 0, 0.509326,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.291206);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.73493,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.688525,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611738,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4052,-99) , 
8, 3.5, 0, 0, 0.458301,-99) , 
5, 0.0454113, 0, 0, 0.508507,-99) , 
4, 0.706246, 0, 0, 0.562866,-99) , 
NN(
0, 
0, 
-1, 3.26923, 0, -1, 0.422178,-99) , 
4, 0.153036, 0, 0, 0.530266,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6498,-99) , 
NN(
0, 
0, 
-1, 4.5, 0, -1, 0.393558,-99) , 
5, 0.102034, 0, 0, 0.452551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.17319,-99) , 
2, 1.04589, 1, 0, 0.383763,-99) , 
7, 0.258539, 1, 0, 0.471193,-99) , 
6, 0.886752, 0, 0, 0.503348,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.235677);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.68392,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642622,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498419,-99) , 
8, 5.38462, 0, 0, 0.546072,-99) , 
9, 0.445769, 1, 0, 0.581686,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.214456, 0, 1, 0.569971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44965,-99) , 
1, 0.738432, 0, 0, 0.531108,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323629,-99) , 
5, 0.0459535, 0, 0, 0.414119,-99) , 
7, 0.229441, 1, 0, 0.49223,-99) , 
NN(
0, 
0, 
-1, 0.17888, 1, -1, 0.334298,-99) , 
0, 0.474654, 1, 0, 0.454858,-99) , 
8, 4.5, 0, 0, 0.496406,-99) , 
6, 0.849184, 0, 0, 0.52314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.212549,-99) , 
0, 1.02155, 1, 0, 0.505367,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.214176);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672477,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481025,-99) , 
6, 0.245316, 0, 0, 0.515666,-99) , 
6, 0.548708, 0, 0, 0.570033,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626766,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588451,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451246,-99) , 
7, 0.113154, 1, 0, 0.489161,-99) , 
6, 0.328701, 0, 0, 0.527253,-99) , 
NN(
0, 
0, 
-1, 4.30769, 0, -1, 0.361301,-99) , 
7, 0.202435, 1, 0, 0.440882,-99) , 
5, 0.0878394, 0, 0, 0.469786,-99) , 
0, 0.238888, 1, 0, 0.5113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254652,-99) , 
0, 1.02155, 1, 0, 0.497222,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.177868);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.0424479, 0, 1, 0.611609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488506,-99) , 
7, 0.47597, 1, 0, 0.581597,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608927,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552498,-99) , 
NN(
0, 
0, 
-1, 0.519794, 1, -1, 0.45825,-99) , 
7, 0.12367, 1, 0, 0.492748,-99) , 
6, 0.511785, 0, 0, 0.532757,-99) , 
NN(
0, 
0, 
-1, 0.615689, 1, -1, 0.408437,-99) , 
7, 0.258539, 1, 0, 0.491343,-99) , 
8, 4.5, 0, 0, 0.524457,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4517,-99) , 
9, 0.632399, 1, 0, 0.493117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.234739,-99) , 
7, 0.207532, 1, 0, 0.397643,-99) , 
2, 1.3, 1, 0, 0.500561,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.205598);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.727907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430558,-99) , 
4, 0.820243, 0, 0, 0.582547,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0494218, 0, 1, 0.54774,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600149,-99) , 
NN(
0, 
0, 
-1, 0.235589, 0, -1, 0.42904,-99) , 
4, 0.341496, 0, 0, 0.50721,-99) , 
NN(
0, 
0, 
-1, 0.483341, 1, -1, 0.395913,-99) , 
4, 0.169397, 0, 0, 0.469117,-99) , 
8, 4.5, 0, 0, 0.499247,-99) , 
4, 0.576177, 0, 0, 0.527332,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451759,-99) , 
0, 0.496443, 1, 0, 0.502468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298053,-99) , 
7, 0.214344, 1, 0, 0.427093,-99) , 
2, 1.11683, 1, 0, 0.501813,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.161882);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711915,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347295,-99) , 
2, 0.86353, 1, 0, 0.457636,-99) , 
4, 0.869056, 0, 0, 0.559447,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578612,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531842,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481599,-99) , 
1, 1.37688, 0, 0, 0.508671,-99) , 
NN(
0, 
0, 
-1, 0.0385712, 0, -1, 0.442197,-99) , 
3, 0.0796547, 0, 0, 0.472918,-99) , 
7, 0.155754, 1, 0, 0.492032,-99) , 
9, 0.22308, 1, 0, 0.505772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41273,-99) , 
8, 2.5, 0, 0, 0.493204,-99) , 
NN(
0, 
0, 
-1, 1.40978, 1, -1, 0.386057,-99) , 
0, 0.676769, 1, 0, 0.476458,-99) , 
4, 0.576177, 0, 0, 0.502563,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.121203);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598189,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559194,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572387,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.594786, 1, 1, 0.538373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490906,-99) , 
3, 0.175944, 1, 0, 0.519079,-99) , 
NN(
0, 
0, 
-1, 0.0472566, 0, -1, 0.465778,-99) , 
3, 0.0912824, 0, 0, 0.488436,-99) , 
NN(
0, 
0, 
-1, 0.844234, 0, -1, 0.413181,-99) , 
8, 2.5, 0, 0, 0.474928,-99) , 
5, 0.0580857, 0, 0, 0.492168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377714,-99) , 
7, 0.405904, 1, 0, 0.479048,-99) , 
5, 0.0928391, 0, 0, 0.488189,-99) , 
6, 0.886752, 0, 0, 0.500208,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.131049);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.443254, 1, 1, 0.588195,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.211632, 0, 1, 0.572225,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551899,-99) , 
NN(
NN(
0, 
0, 
-1, 0.958169, 0, 1, 0.528408,-99) , 
NN(
0, 
0, 
-1, 0.239831, 1, -1, 0.436481,-99) , 
1, 0.895072, 0, 0, 0.487589,-99) , 
7, 0.0969939, 1, 0, 0.499278,-99) , 
9, 0.334793, 1, 0, 0.516949,-99) , 
NN(
0, 
0, 
-1, 0.734646, 1, -1, 0.425066,-99) , 
7, 0.297072, 1, 0, 0.497638,-99) , 
5, 0.0753939, 0, 0, 0.510785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368118,-99) , 
7, 0.759476, 1, 0, 0.503044,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.117232);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470754,-99) , 
2, 0.442539, 0, 0, 0.519838,-99) , 
6, 0.511146, 0, 0, 0.545875,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556789,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510188,-99) , 
NN(
0, 
0, 
-1, 0.48271, 1, -1, 0.473104,-99) , 
5, 0.0488455, 1, 0, 0.485705,-99) , 
NN(
0, 
0, 
-1, 0.219672, 1, -1, 0.438339,-99) , 
1, 1.23505, 0, 0, 0.461697,-99) , 
5, 0.103765, 0, 0, 0.479589,-99) , 
0, 0.226307, 1, 0, 0.511546,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458777,-99) , 
1, 0.844525, 0, 0, 0.498524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365834,-99) , 
7, 0.214344, 1, 0, 0.451658,-99) , 
2, 1.11683, 1, 0, 0.496469,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.117584);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584847,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558389,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56331,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.883517, 0, 1, 0.55202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469132,-99) , 
0, 0.416237, 1, 0, 0.522632,-99) , 
NN(
0, 
0, 
-1, 0.59456, 1, -1, 0.46662,-99) , 
8, 3.26923, 1, 0, 0.497289,-99) , 
NN(
0, 
0, 
-1, 1.18123, 0, -1, 0.419277,-99) , 
7, 0.239768, 1, 0, 0.474923,-99) , 
1, 1.65915, 0, 0, 0.482169,-99) , 
0, 0.140147, 1, 0, 0.498396,-99) , 
5, 0.0753939, 0, 0, 0.508207,-99) , 
NN(
0, 
0, 
-1, 0.702322, 1, -1, 0.431448,-99) , 
7, 0.509007, 1, 0, 0.498878,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.133307);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673563,-99) , 
NN(
0, 
0, 
-1, 0.700088, 0, -1, 0.442793,-99) , 
4, 0.869056, 0, 0, 0.533943,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474642,-99) , 
5, 0.0496536, 0, 0, 0.501622,-99) , 
4, 0.404076, 0, 0, 0.534564,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467914,-99) , 
2, 0.905592, 0, 0, 0.491657,-99) , 
4, 0.169397, 0, 0, 0.518943,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51633,-99) , 
NN(
0, 
0, 
-1, 0.184437, 1, -1, 0.45306,-99) , 
8, 4.5, 0, 0, 0.475422,-99) , 
6, 0.151839, 0, 0, 0.503957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42116,-99) , 
6, 0.698711, 1, 0, 0.486733,-99) , 
4, 0.576177, 0, 0, 0.501377,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0846323);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586352,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551906,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49318,-99) , 
0, 0.443046, 0, 0, 0.532491,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499126,-99) , 
2, 0.850154, 0, 0, 0.536873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47992,-99) , 
8, 3.34615, 1, 0, 0.509098,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4369,-99) , 
1, 1.14208, 0, 0, 0.466209,-99) , 
1, 1.00346, 1, 0, 0.495209,-99) , 
1, 1.30381, 0, 0, 0.505209,-99) , 
NN(
0, 
0, 
-1, 0.32109, 0, -1, 0.462634,-99) , 
7, 0.471799, 1, 0, 0.498751,-99) , 
NN(
0, 
0, 
-1, 0.257416, 0, -1, 0.458887,-99) , 
8, 2.5, 0, 0, 0.493591,-99) , 
9, 0.148798, 1, 0, 0.500023,-99) , 
6, 0.886752, 0, 0, 0.509274,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.14357);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441736,-99) , 
4, 0.77143, 0, 0, 0.546174,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.15385, 1, 1, 0.591889,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463766,-99) , 
1, 1.17408, 0, 0, 0.506942,-99) , 
0, 0.303208, 1, 0, 0.549241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458799,-99) , 
6, 0.623905, 1, 0, 0.526679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447042,-99) , 
2, 0.379327, 0, 0, 0.510375,-99) , 
NN(
0, 
0, 
-1, 0.446312, 0, -1, 0.4333,-99) , 
0, 0.676769, 1, 0, 0.498774,-99) , 
4, 0.576177, 0, 0, 0.513377,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.102548);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587226,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593926,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456855,-99) , 
8, 4.5, 0, 0, 0.497,-99) , 
3, 0.0788721, 1, 0, 0.545199,-99) , 
NN(
NN(
0, 
0, 
-1, 0.351617, 0, 1, 0.527999,-99) , 
NN(
NN(
0, 
0, 
-1, 3.38462, 1, 1, 0.528814,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403426,-99) , 
3, 0.0404152, 0, 0, 0.461969,-99) , 
3, 0.0786461, 0, 0, 0.49219,-99) , 
5, 0.0383287, 0, 0, 0.503263,-99) , 
5, 0.0517457, 0, 0, 0.519559,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473021,-99) , 
2, 0.92665, 0, 0, 0.508865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451203,-99) , 
7, 0.240042, 1, 0, 0.488305,-99) , 
6, 0.154461, 0, 0, 0.509852,-99) , 
6, 0.886752, 0, 0, 0.518138,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.103558);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588109,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474852,-99) , 
7, 0.234298, 0, 0, 0.505706,-99) , 
6, 0.548685, 0, 0, 0.533727,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 3.15385, 1, 1, 0.539953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44613,-99) , 
1, 0.674512, 0, 0, 0.523412,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534501,-99) , 
NN(
0, 
0, 
-1, 0.91452, 1, -1, 0.458196,-99) , 
8, 5.26923, 0, 0, 0.484323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.337934,-99) , 
8, 3.5, 0, 0, 0.447056,-99) , 
7, 0.240042, 1, 0, 0.494856,-99) , 
2, 0.567293, 1, 0, 0.508768,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0855488);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.557718, 1, 1, 0.538153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538701,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531017,-99) , 
NN(
0, 
0, 
-1, 0.0398028, 0, -1, 0.470822,-99) , 
2, 0.944144, 0, 0, 0.486505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41907,-99) , 
7, 0.369238, 1, 0, 0.471377,-99) , 
1, 2.24031, 0, 0, 0.487716,-99) , 
0, 0.226307, 1, 0, 0.511988,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525433,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423549,-99) , 
7, 0.129053, 1, 0, 0.472534,-99) , 
1, 0.954121, 0, 0, 0.492826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409806,-99) , 
0, 0.745655, 1, 0, 0.47015,-99) , 
2, 1.11683, 1, 0, 0.501521,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0797992);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56264,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496325,-99) , 
9, 0.171689, 1, 0, 0.498618,-99) , 
5, 0.0438897, 0, 0, 0.533128,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520817,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536056,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496182,-99) , 
5, 0.0427982, 1, 0, 0.522248,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446443,-99) , 
1, 1.21625, 0, 0, 0.471444,-99) , 
8, 3.38462, 1, 0, 0.491853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43729,-99) , 
1, 0.792835, 0, 0, 0.47855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422962,-99) , 
7, 0.327189, 1, 0, 0.470074,-99) , 
1, 1.89375, 0, 0, 0.479425,-99) , 
0, 0.161655, 1, 0, 0.489358,-99) , 
9, 0.297594, 1, 0, 0.499703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418906,-99) , 
7, 0.759476, 1, 0, 0.49541,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0726177);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545832,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.500467, 0, 1, 0.522321,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48494,-99) , 
6, 0.287817, 0, 0, 0.503456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410591,-99) , 
1, 1.07188, 0, 0, 0.478674,-99) , 
0, 0.286655, 1, 0, 0.50211,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472002,-99) , 
1, 0.983961, 0, 0, 0.490236,-99) , 
NN(
0, 
0, 
-1, 0.536145, 0, -1, 0.45153,-99) , 
2, 0.722085, 0, 0, 0.469603,-99) , 
9, 0.594878, 1, 0, 0.488175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441514,-99) , 
2, 1.41272, 1, 0, 0.483285,-99) , 
2, 2.03271, 0, 0, 0.486833,-99) , 
6, 0.886752, 0, 0, 0.492745,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.107081);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588285,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46298,-99) , 
2, 0.831831, 1, 0, 0.502131,-99) , 
1, 1.01475, 1, 0, 0.528297,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476812,-99) , 
6, 0.247718, 1, 0, 0.508918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423209,-99) , 
4, 0.566164, 1, 0, 0.473949,-99) , 
5, 0.0426408, 0, 0, 0.502652,-99) , 
NN(
0, 
0, 
-1, 4.5, 1, -1, 0.439169,-99) , 
4, 0.263273, 0, 0, 0.484381,-99) , 
4, 0.869056, 0, 0, 0.500207,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472201,-99) , 
7, 0.129184, 0, 0, 0.491661,-99) , 
NN(
0, 
0, 
-1, 4.30769, 0, -1, 0.434012,-99) , 
7, 0.203822, 1, 0, 0.463042,-99) , 
4, 0.15313, 0, 0, 0.491791,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.084087);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542069,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537891,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546176,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484958,-99) , 
6, 0.211097, 0, 0, 0.520852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450218,-99) , 
0, 0.294011, 1, 0, 0.507188,-99) , 
2, 0.90271, 0, 0, 0.517522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441353,-99) , 
1, 0.687337, 0, 0, 0.50839,-99) , 
NN(
0, 
0, 
-1, 0.593555, 1, -1, 0.466945,-99) , 
8, 4.5, 1, 0, 0.495342,-99) , 
NN(
0, 
0, 
-1, 3.38462, 0, -1, 0.443243,-99) , 
0, 0.540015, 1, 0, 0.487219,-99) , 
1, 2.13065, 0, 0, 0.492114,-99) , 
7, 0.094771, 1, 0, 0.49857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435184,-99) , 
7, 0.759476, 1, 0, 0.495224,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0789152);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.15385, 1, 1, 0.544092,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58756,-99) , 
NN(
NN(
0, 
0, 
-1, 1.05689, 1, 1, 0.514501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426121,-99) , 
8, 3.5, 0, 0, 0.480594,-99) , 
6, 0.386161, 0, 0, 0.505456,-99) , 
0, 0.364636, 1, 0, 0.525246,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394751,-99) , 
4, 0.738888, 0, 0, 0.474402,-99) , 
4, 0.576177, 1, 0, 0.510377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473571,-99) , 
6, 0.698614, 1, 0, 0.502861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473308,-99) , 
2, 0.384115, 0, 0, 0.497092,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.063254);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549959,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54033,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.364448, 1, 1, 0.534315,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482797,-99) , 
2, 0.718215, 0, 0, 0.49446,-99) , 
9, 0.557364, 1, 0, 0.512848,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481793,-99) , 
0, 0.746463, 1, 0, 0.506309,-99) , 
NN(
0, 
0, 
-1, 0.0358499, 1, -1, 0.464337,-99) , 
1, 1.38095, 0, 0, 0.482195,-99) , 
3, 0.0912824, 1, 0, 0.497286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471579,-99) , 
2, 0.405249, 0, 0, 0.491562,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456732,-99) , 
8, 2.5, 0, 0, 0.487419,-99) , 
2, 2.03271, 0, 0, 0.490414,-99) , 
6, 0.886752, 0, 0, 0.49665,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0855727);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594947,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56495,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447331,-99) , 
4, 0.818126, 0, 0, 0.482689,-99) , 
4, 0.571171, 1, 0, 0.506655,-99) , 
6, 0.660918, 0, 0, 0.526938,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519076,-99) , 
NN(
0, 
0, 
-1, 0.55731, 1, -1, 0.475415,-99) , 
8, 3.38462, 1, 0, 0.492374,-99) , 
NN(
0, 
0, 
-1, 0.409121, 1, -1, 0.461196,-99) , 
4, 0.233234, 0, 0, 0.478809,-99) , 
4, 0.413467, 0, 0, 0.505695,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477269,-99) , 
2, 0.806438, 0, 0, 0.497471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440413,-99) , 
8, 3.38462, 0, 0, 0.475659,-99) , 
4, 0.15313, 0, 0, 0.498893,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0712422);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538654,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527301,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529895,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558295,-99) , 
NN(
NN(
0, 
0, 
-1, 1.28444, 0, 1, 0.527504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467396,-99) , 
7, 0.183114, 1, 0, 0.509241,-99) , 
1, 1.14827, 0, 0, 0.521949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47302,-99) , 
2, 0.66013, 0, 0, 0.507883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461341,-99) , 
7, 0.386256, 1, 0, 0.500432,-99) , 
NN(
0, 
0, 
-1, 0.755159, 0, -1, 0.45599,-99) , 
4, 0.576177, 1, 0, 0.487242,-99) , 
0, 0.146283, 1, 0, 0.496756,-99) , 
1, 2.65961, 0, 0, 0.499024,-99) , 
6, 0.849124, 0, 0, 0.504126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464473,-99) , 
3, 0.264553, 1, 0, 0.50099,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0853153);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597218,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474257,-99) , 
6, 0.322521, 0, 0, 0.496676,-99) , 
3, 0.0414801, 1, 0, 0.537216,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457158,-99) , 
7, 0.536983, 1, 0, 0.49865,-99) , 
NN(
0, 
0, 
-1, 0.184342, 1, -1, 0.462287,-99) , 
1, 1.64816, 0, 0, 0.480792,-99) , 
3, 0.0878405, 1, 0, 0.510444,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488246,-99) , 
8, 3.26923, 1, 0, 0.528038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471376,-99) , 
0, 0.46764, 1, 0, 0.509786,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477278,-99) , 
3, 0.0571698, 0, 0, 0.497761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403766,-99) , 
3, 0.0305621, 0, 0, 0.473201,-99) , 
3, 0.0882121, 0, 0, 0.489458,-99) , 
5, 0.0426408, 0, 0, 0.49985,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0596223);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547538,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49427,-99) , 
3, 0.0502667, 1, 0, 0.534354,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473724,-99) , 
0, 0.724394, 0, 0, 0.489108,-99) , 
3, 0.089965, 1, 0, 0.513959,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.400952, 1, 1, 0.520261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477996,-99) , 
8, 3.26923, 1, 0, 0.498293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469528,-99) , 
6, 0.510889, 1, 0, 0.489102,-99) , 
5, 0.0426408, 0, 0, 0.501984,-99) , 
4, 0.869056, 0, 0, 0.508917,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48233,-99) , 
8, 3.38462, 0, 0, 0.500663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454036,-99) , 
6, 0.510582, 1, 0, 0.485943,-99) , 
4, 0.15313, 0, 0, 0.503703,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0576096);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.24815, 0, 1, 0.538477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48798,-99) , 
7, 0.326505, 1, 0, 0.52503,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537828,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521186,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.828759, 0, 1, 0.518574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473124,-99) , 
7, 0.35678, 1, 0, 0.508344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47625,-99) , 
8, 5.5, 1, 0, 0.501278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445019,-99) , 
1, 0.831717, 0, 0, 0.490058,-99) , 
0, 0.161655, 1, 0, 0.49755,-99) , 
9, 0.889916, 0, 0, 0.501382,-99) , 
9, 0.297594, 1, 0, 0.506959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463585,-99) , 
7, 0.759476, 1, 0, 0.504657,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0555166);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563729,-99) , 
NN(
NN(
0, 
0, 
-1, 1.42475, 0, 1, 0.54042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479317,-99) , 
0, 0.344928, 0, 0, 0.50351,-99) , 
6, 0.660918, 0, 0, 0.517192,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.818487, 0, 1, 0.515499,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463354,-99) , 
3, 0.0891564, 1, 0, 0.481848,-99) , 
6, 0.183669, 0, 0, 0.500269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465824,-99) , 
6, 0.62348, 1, 0, 0.491508,-99) , 
4, 0.413467, 0, 0, 0.505825,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509224,-99) , 
NN(
0, 
0, 
-1, 0.818163, 0, -1, 0.484023,-99) , 
9, 0.632052, 0, 0, 0.492759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465263,-99) , 
6, 0.510582, 1, 0, 0.484092,-99) , 
4, 0.15313, 0, 0, 0.500892,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0641801);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531842,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480919,-99) , 
5, 0.0560407, 0, 0, 0.499548,-99) , 
0, 0.344928, 1, 0, 0.51692,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548655,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485948,-99) , 
1, 0.842541, 0, 0, 0.506636,-99) , 
7, 0.13528, 1, 0, 0.527821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443762,-99) , 
1, 0.601003, 0, 0, 0.511972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47536,-99) , 
1, 1.01968, 1, 0, 0.504549,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.579709, 1, 1, 0.520333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462581,-99) , 
1, 1.24846, 0, 0, 0.506376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46293,-99) , 
7, 0.608426, 1, 0, 0.498422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444978,-99) , 
1, 0.999128, 0, 0, 0.487496,-99) , 
7, 0.213455, 1, 0, 0.496443,-99) , 
9, 0.297594, 1, 0, 0.501468,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0526214);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526026,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544597,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473047,-99) , 
0, 0.199755, 1, 0, 0.501259,-99) , 
2, 0.700994, 0, 0, 0.511306,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544391,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476908,-99) , 
0, 0.669371, 1, 0, 0.496026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446084,-99) , 
8, 3.5, 0, 0, 0.474697,-99) , 
2, 0.689197, 1, 0, 0.490259,-99) , 
0, 0.343243, 1, 0, 0.502086,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503712,-99) , 
NN(
0, 
0, 
-1, 0.0590873, 0, -1, 0.473094,-99) , 
7, 0.164956, 1, 0, 0.485745,-99) , 
9, 0.686752, 1, 0, 0.497521,-99) , 
9, 0.892777, 0, 0, 0.499402,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0600735);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530641,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518582,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534822,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486421,-99) , 
2, 0.560102, 0, 0, 0.504389,-99) , 
0, 0.686491, 0, 0, 0.513987,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.849287, 0, 1, 0.543688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485737,-99) , 
8, 3.15385, 1, 0, 0.512494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472983,-99) , 
6, 0.404134, 1, 0, 0.500341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459451,-99) , 
2, 0.40795, 0, 0, 0.489794,-99) , 
NN(
0, 
0, 
-1, 1.42603, 0, -1, 0.449385,-99) , 
0, 0.39186, 1, 0, 0.481933,-99) , 
1, 1.42097, 0, 0, 0.491631,-99) , 
6, 0.849124, 0, 0, 0.495046,-99) , 
2, 2.03271, 0, 0, 0.497011,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0635156);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530415,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548246,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535865,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49636,-99) , 
1, 1.73377, 0, 0, 0.512501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446546,-99) , 
1, 1.28354, 0, 0, 0.492271,-99) , 
0, 0.316701, 1, 0, 0.50961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480196,-99) , 
2, 0.483757, 0, 0, 0.501625,-99) , 
2, 1.27544, 0, 0, 0.507417,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541712,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469329,-99) , 
0, 0.262414, 1, 0, 0.488449,-99) , 
2, 1.48077, 0, 0, 0.502716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433122,-99) , 
7, 0.180846, 1, 0, 0.48145,-99) , 
1, 0.958384, 0, 0, 0.496661,-99) , 
0, 0.130094, 1, 0, 0.502553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468454,-99) , 
0, 0.82312, 1, 0, 0.500419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470565,-99) , 
7, 0.759476, 1, 0, 0.498834,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0717121);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478416,-99) , 
6, 0.212798, 0, 0, 0.536233,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535697,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472893,-99) , 
0, 0.454825, 0, 0, 0.487951,-99) , 
0, 0.689421, 0, 0, 0.500443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462203,-99) , 
8, 3.5, 0, 0, 0.494964,-99) , 
1, 0.992869, 1, 0, 0.506585,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530089,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477223,-99) , 
1, 0.982237, 1, 0, 0.517757,-99) , 
NN(
0, 
0, 
-1, 0.023802, 1, -1, 0.479066,-99) , 
1, 0.878599, 0, 0, 0.498574,-99) , 
NN(
0, 
0, 
-1, 0.034026, 0, -1, 0.452634,-99) , 
3, 0.0589481, 0, 0, 0.479916,-99) , 
1, 1.178, 0, 0, 0.489589,-99) , 
5, 0.0426408, 0, 0, 0.498011,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.084418);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529596,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560114,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481226,-99) , 
3, 0.0750915, 1, 0, 0.521104,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537483,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440979,-99) , 
0, 0.296703, 1, 0, 0.501622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428173,-99) , 
2, 0.597011, 0, 0, 0.478488,-99) , 
1, 1.2701, 0, 0, 0.49316,-99) , 
5, 0.0557459, 0, 0, 0.503276,-99) , 
2, 1.32577, 0, 0, 0.508313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453131,-99) , 
1, 0.68546, 0, 0, 0.502836,-99) , 
0, 0.123334, 1, 0, 0.50757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450202,-99) , 
8, 4.30769, 0, 0, 0.479229,-99) , 
0, 0.624154, 1, 0, 0.503673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477103,-99) , 
3, 0.264553, 1, 0, 0.501571,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0576901);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532091,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534918,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482701,-99) , 
9, 0.557659, 0, 0, 0.496436,-99) , 
2, 0.637743, 1, 0, 0.517941,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507476,-99) , 
NN(
0, 
0, 
-1, 0.133127, 0, -1, 0.476169,-99) , 
3, 0.0908495, 1, 0, 0.491965,-99) , 
6, 0.28468, 0, 0, 0.505769,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.631839, 1, 1, 0.539118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492379,-99) , 
5, 0.031056, 1, 0, 0.521477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459711,-99) , 
3, 0.0453342, 0, 0, 0.500088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439845,-99) , 
0, 0.412359, 1, 0, 0.489997,-99) , 
5, 0.0426408, 0, 0, 0.498038,-99) , 
2, 2.03271, 0, 0, 0.499921,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0549029);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.0459855, 0, 1, 0.548912,-99) , 
NN(
NN(
0, 
0, 
-1, 3.15385, 1, 1, 0.54195,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475856,-99) , 
7, 0.235186, 1, 0, 0.491317,-99) , 
0, 0.338329, 1, 0, 0.514833,-99) , 
6, 0.426676, 0, 0, 0.523191,-99) , 
NN(
0, 
0, 
-1, 0.706346, 0, -1, 0.480461,-99) , 
4, 0.576177, 1, 0, 0.510793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467776,-99) , 
6, 0.773869, 1, 0, 0.503623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481191,-99) , 
2, 0.384115, 0, 0, 0.499242,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0656568);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.520476, 1, 1, 0.531637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474761,-99) , 
4, 0.673804, 0, 0, 0.519234,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544059,-99) , 
NN(
NN(
0, 
0, 
-1, 3.15385, 1, 1, 0.528843,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518234,-99) , 
NN(
0, 
0, 
-1, 3.38462, 0, -1, 0.480339,-99) , 
9, 0.706783, 0, 0, 0.490961,-99) , 
0, 0.364636, 1, 0, 0.510346,-99) , 
6, 0.54246, 0, 0, 0.515425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442614,-99) , 
6, 0.773942, 1, 0, 0.503273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458407,-99) , 
2, 0.379327, 0, 0, 0.495262,-99) , 
4, 0.576177, 0, 0, 0.502512,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0436011);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53506,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548355,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494498,-99) , 
2, 1.43914, 0, 0, 0.507671,-99) , 
2, 0.823431, 1, 0, 0.521152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48156,-99) , 
2, 0.580076, 0, 0, 0.492005,-99) , 
0, 0.344928, 0, 0, 0.505256,-99) , 
6, 0.736157, 0, 0, 0.510981,-99) , 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.210122, 1, 1, 0.520063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499743,-99) , 
9, 0.761152, 1, 0, 0.510558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476516,-99) , 
4, 0.250622, 0, 0, 0.503112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477389,-99) , 
4, 0.152996, 0, 0, 0.497795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456073,-99) , 
8, 5.5, 1, 0, 0.49038,-99) , 
9, 0.520787, 1, 0, 0.50017,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0510075);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540799,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495871,-99) , 
8, 3.38462, 0, 0, 0.508885,-99) , 
9, 0.0801225, 1, 0, 0.515768,-99) , 
NN(
NN(
0, 
0, 
-1, 2.19197, 1, 1, 0.516679,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 3.15385, 1, 1, 0.53173,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518924,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455671,-99) , 
1, 1.25781, 0, 0, 0.475966,-99) , 
0, 0.191057, 1, 0, 0.496653,-99) , 
2, 0.954339, 0, 0, 0.505643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460104,-99) , 
1, 0.633336, 0, 0, 0.499634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462058,-99) , 
0, 0.544235, 1, 0, 0.494058,-99) , 
5, 0.0762154, 0, 0, 0.497606,-99) , 
9, 0.297594, 1, 0, 0.502051,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0397355);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522615,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486253,-99) , 
3, 0.0862047, 0, 0, 0.501388,-99) , 
6, 0.322303, 0, 0, 0.511268,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522973,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522223,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481189,-99) , 
4, 0.598708, 1, 0, 0.492472,-99) , 
7, 0.209238, 1, 0, 0.507992,-99) , 
NN(
0, 
0, 
-1, 0.210122, 0, -1, 0.482528,-99) , 
4, 0.348383, 0, 0, 0.4987,-99) , 
NN(
0, 
0, 
-1, 3.03846, 0, -1, 0.478866,-99) , 
4, 0.15313, 0, 0, 0.494176,-99) , 
9, 0.864163, 0, 0, 0.49833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475643,-99) , 
8, 5.5, 1, 0, 0.494224,-99) , 
9, 0.297594, 1, 0, 0.498397,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0463886);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516555,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542237,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473686,-99) , 
7, 0.163572, 0, 0, 0.501899,-99) , 
2, 1.56209, 0, 0, 0.519951,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496579,-99) , 
1, 2.43899, 0, 0, 0.51198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459981,-99) , 
5, 0.0548519, 0, 0, 0.496113,-99) , 
7, 0.259428, 1, 0, 0.507924,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520933,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50123,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4804,-99) , 
7, 0.158564, 0, 0, 0.492096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436525,-99) , 
5, 0.0388457, 1, 0, 0.470687,-99) , 
3, 0.0451973, 1, 0, 0.482342,-99) , 
7, 0.30689, 0, 0, 0.489606,-99) , 
0, 0.344928, 0, 0, 0.497272,-99) , 
6, 0.886752, 0, 0, 0.499249,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0527013);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527567,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494497,-99) , 
7, 0.342594, 1, 0, 0.523448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483536,-99) , 
1, 1.10267, 0, 0, 0.510088,-99) , 
6, 0.407126, 0, 0, 0.520436,-99) , 
NN(
0, 
0, 
-1, 0.0635603, 1, -1, 0.480676,-99) , 
0, 0.326245, 0, 0, 0.500301,-99) , 
6, 0.736624, 0, 0, 0.505293,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483539,-99) , 
8, 3.38462, 1, 0, 0.503126,-99) , 
NN(
0, 
0, 
-1, 0.0353686, 0, -1, 0.467133,-99) , 
3, 0.0765844, 0, 0, 0.484804,-99) , 
5, 0.0339182, 0, 0, 0.497553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469305,-99) , 
7, 0.759476, 1, 0, 0.496049,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0496085);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.5, 0, 1, 0.52001,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523265,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509141,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479142,-99) , 
0, 0.383637, 1, 0, 0.508195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45892,-99) , 
8, 3.15385, 1, 0, 0.48617,-99) , 
0, 0.202296, 1, 0, 0.494877,-99) , 
5, 0.0572766, 0, 0, 0.499601,-99) , 
1, 1.41907, 0, 0, 0.505414,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514646,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485488,-99) , 
2, 0.886313, 0, 0, 0.505927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458178,-99) , 
6, 0.76808, 1, 0, 0.486104,-99) , 
4, 0.576177, 0, 0, 0.494787,-99) , 
6, 0.397593, 1, 0, 0.501092,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0459279);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51892,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494463,-99) , 
8, 4.30769, 1, 0, 0.514896,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493837,-99) , 
1, 0.924443, 0, 0, 0.509825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474095,-99) , 
7, 0.241253, 1, 0, 0.49965,-99) , 
1, 1.17921, 0, 0, 0.50647,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.517665, 1, 1, 0.525496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485849,-99) , 
2, 0.758143, 0, 0, 0.506346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466745,-99) , 
1, 0.806511, 0, 0, 0.495909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461265,-99) , 
8, 5.5, 1, 0, 0.489325,-99) , 
9, 0.483588, 1, 0, 0.496623,-99) , 
7, 0.094771, 1, 0, 0.499523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476917,-99) , 
7, 0.759476, 1, 0, 0.498319,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0550779);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517339,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53777,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543182,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480223,-99) , 
7, 0.331436, 0, 0, 0.495098,-99) , 
2, 0.822356, 0, 0, 0.507747,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48624,-99) , 
1, 0.71002, 1, 0, 0.504916,-99) , 
NN(
0, 
0, 
-1, 0.802588, 0, -1, 0.464643,-99) , 
7, 0.142799, 1, 0, 0.486059,-99) , 
1, 0.944548, 0, 0, 0.498186,-99) , 
6, 0.81177, 0, 0, 0.504077,-99) , 
NN(
0, 
0, 
-1, 0.339099, 1, -1, 0.472721,-99) , 
0, 0.566118, 1, 0, 0.498957,-99) , 
1, 2.65961, 0, 0, 0.500357,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }
inline void ReadBDT::InitTransform_Identity_1() {}

inline void ReadBDT::Transform_Identity_1(const std::vector<double> &, int) const {}

//_______________________________________________________________________
inline void ReadBDT::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadBDT::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
